// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';
import type { AxiosError } from 'axios';

import { client } from '../client.gen';
import { controlService, deleteEventDir, deleteEventFile, firmwareUpgrade, getConfigs, getEventDirs, getEventFiles, getHostname, getLastRecordedVideo, getLinks, getSnapshot, getStatus, loadConfig, type Options, playAudio, playAudioFile, ptzMove, ptzPreset, reboot, resetConfig, saveConfig, setCameraSettings, setConfigs, speakText, startRecording, testProxy, timelapse, wifi } from '../sdk.gen';
import type { ControlServiceData, ControlServiceResponse, DeleteEventDirData, DeleteEventDirResponse, DeleteEventFileData, DeleteEventFileResponse, FirmwareUpgradeData, FirmwareUpgradeResponse, GetConfigsData, GetConfigsResponse2, GetEventDirsData, GetEventDirsResponse, GetEventFilesData, GetEventFilesResponse, GetHostnameData, GetHostnameResponse, GetLastRecordedVideoData, GetLastRecordedVideoResponse, GetLinksData, GetLinksResponse, GetSnapshotData, GetSnapshotResponse, GetStatusData, GetStatusResponse, LoadConfigData, LoadConfigResponse, PlayAudioData, PlayAudioFileData, PlayAudioFileResponse, PlayAudioResponse, PtzMoveData, PtzMoveResponse, PtzPresetData, PtzPresetResponse, RebootData, RebootResponse, ResetConfigData, ResetConfigResponse, SaveConfigData, SaveConfigResponse, SetCameraSettingsData, SetCameraSettingsResponse, SetConfigsData, SetConfigsResponse, SpeakTextData, SpeakTextResponse, StartRecordingData, StartRecordingResponse, TestProxyData, TestProxyResponse, TimelapseData, TimelapseResponse, WifiData, WifiResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: options?.baseURL || (options?.client ?? client).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const setCameraSettingsQueryKey = (options?: Options<SetCameraSettingsData>) => createQueryKey('setCameraSettings', options);

/**
 * Apply camera feature settings (mutating GET)
 *
 * Applies camera settings by issuing ipc_cmd hardware calls per recognised
 * parameter. Despite being a GET this MUTATES device state.
 *
 * Behavioral facts:
 * - At most 15 query parameters are parsed (`for I in 1 2 ... 15`); a 16th
 * param is silently discarded. The stock UI sends exactly 15.
 * - Binary params (switch_on, save_video_on_motion, face_detection,
 * motion_tracking, sound_detection, led, ir, rotate, and the ai_*
 * detections) are NOT strict yes/no: only the exact value `no` means OFF;
 * ANY other value (including `yes`, `foo`, empty) means ON.
 * - True enum params (motion_detection, sensitivity, sound_sensitivity,
 * cruise) have NO else branch: an out-of-domain value is silently dropped
 * (no command run) yet the request still returns `{"error":"false"}`.
 * - Omitting a param issues no command for it (leaves current state).
 * - ai_vehicle_detection and ai_animal_detection are only honoured on 11/12
 * firmware AND only when motion_detection=no; otherwise ignored.
 * - Every parameter name and value is run through validateString, which
 * REJECTS any of `' ! " @ # $ % & ^ * ( ) . , : ;` (note `.` and `&` are
 * rejected). A rejected value returns `{"error":"true"}`.
 * - Worst-case latency ~9 seconds: an unconditional `sleep 0.5` runs on each
 * of up to 15 loop iterations (~7.5s), plus `sleep 1` when switch_on=no,
 * plus `sleep 0.5` when cruise is presets or 360.
 */
export const setCameraSettingsOptions = (options?: Options<SetCameraSettingsData>) => queryOptions<SetCameraSettingsResponse, AxiosError<DefaultError>, SetCameraSettingsResponse, ReturnType<typeof setCameraSettingsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await setCameraSettings({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: setCameraSettingsQueryKey(options)
});

export const getConfigsQueryKey = (options?: Options<GetConfigsData>) => createQueryKey('getConfigs', options);

/**
 * Read a .conf file as JSON
 *
 * Returns the raw `KEY=VALUE` contents of a chosen `.conf` file as a JSON
 * object of string values.
 *
 * Behavioral facts:
 * - The `conf` value selects the file `etc/<conf>.conf`, EXCEPT `mqtt` which
 * is remapped to `etc/mqttv4.conf`. There is NO real enum in the script:
 * any value that clears the validateQueryString blocklist is accepted and
 * interpolated straight into the file path (so `.` and `/` enable path
 * traversal reads). The enum below is the set of values the firmware and
 * stock UI actually use; other values simply read a different / missing
 * file.
 * - A conf value pointing at a missing file is NOT an error: you get HTTP
 * 200 with a body of just `{"NULL":"NULL"}`.
 * - EVERY response ends with a fake `"NULL":"NULL"` pair whose only purpose
 * is to absorb the trailing comma left by the sed transform. Clients MUST
 * ignore/strip the NULL key.
 * - `conf` must be the ONLY query parameter: the script does `cut -d'='` on
 * the whole QUERY_STRING and does not split on `&`, so `conf=camera&x=y`
 * becomes the value `camera&x` and breaks the lookup.
 * - Special output: `conf=system` also appends HOSTNAME; `conf=camera` also
 * appends HOMEVER (injected RAW/unescaped); `conf=proxychains` returns a
 * single PROXYCHAINS_SERVERS string built from the [ProxyList] section.
 * - Values are only partially escaped; a stray quote/backslash can yield
 * malformed JSON. Parse defensively.
 *
 * The generic response is modelled as an open string map. Named component
 * schemas (CameraConf, SystemConf, MqttConf, MqttAdvertiseConf,
 * PtzPresetsConf, ProxychainsConf) document the well-known files but cannot
 * be referenced here because OpenAPI 3.0 cannot switch a response schema on
 * a query-param value.
 */
export const getConfigsOptions = (options?: Options<GetConfigsData>) => queryOptions<GetConfigsResponse2, AxiosError<DefaultError>, GetConfigsResponse2, ReturnType<typeof getConfigsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getConfigs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getConfigsQueryKey(options)
});

/**
 * Write keys into a .conf file
 *
 * Writes keys into the `.conf` file selected by the `conf` query parameter.
 *
 * Behavioral facts:
 * - Body is a single line of JSON (read via `read -r`, first line only) that
 * must be a valid JSON object (checked by `jq -e`). The stock UI sends a
 * one-line `JSON.stringify` object, so this works; a genuinely multi-line
 * body would be truncated.
 * - Interpreted as a flat map KEY -> value. Each KEY is checked by validateKey
 * (rejects `| \ / ' ! " @ # $ % & ^ * ( ) . , : ; { } = ?`); a bad KEY
 * returns `{"error":"true"}`. VALUES are generally NOT validated.
 * - Generic keys are written with `sed -i` only if a `^KEY=` line ALREADY
 * exists in the target file; unknown keys are accepted (error=false) but
 * write nothing.
 * - Special keys: HOSTNAME (also runs `hostname`, derives yi-<mac>/yi-hack
 * when empty), MOTION_IMAGE_DELAY (only written if numeric AND <= 5.0),
 * PROXYCHAINS_SERVERS (rebuilds the whole file from `<file>.template`),
 * TIMELAPSE_DT (whitelist: 1,2,3,4,5,6,10,15,20,30,60,120,180,240,360,1440
 * or the form `1440+<n>` with n <= 1440). Out-of-range/invalid special
 * values are silently dropped yet still return error=false.
 * - As with get_configs, `conf` is interpolated into the file path and can
 * enable path-traversal writes; `mqtt` maps to mqttv4.conf.
 */
export const setConfigsMutation = (options?: Partial<Options<SetConfigsData>>): UseMutationOptions<SetConfigsResponse, AxiosError<DefaultError>, Options<SetConfigsData>> => {
    const mutationOptions: UseMutationOptions<SetConfigsResponse, AxiosError<DefaultError>, Options<SetConfigsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await setConfigs({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getStatusQueryKey = (options?: Options<GetStatusData>) => createQueryKey('getStatus', options);

/**
 * Get device status telemetry
 *
 * Returns a single JSON object of device telemetry. Read-only; a single
 * unconditional code path with no error branch. All query parameters are
 * silently ignored (no parsing). All values are quoted JSON strings.
 *
 * Quirks: `ptz` is `yes` only for an allowlist of model suffixes; `go2rtc`
 * is `yes` only if the go2rtc binary exists; `free_sd` is the FREE percent
 * (or `N/A`); `serial_number` can be empty. Values are interpolated raw with
 * no escaping, so an exotic hostname/ESSID could break the JSON.
 */
export const getStatusOptions = (options?: Options<GetStatusData>) => queryOptions<GetStatusResponse, AxiosError<DefaultError>, GetStatusResponse, ReturnType<typeof getStatusQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getStatus({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getStatusQueryKey(options)
});

export const getHostnameQueryKey = (options?: Options<GetHostnameData>) => createQueryKey('getHostname', options);

/**
 * Get hostname as a JavaScript snippet
 *
 * NOT JSON. Emits `text/javascript` loaded via a `script` tag; the body is
 * a single statement `hostname="<value>";` that sets a global variable.
 * The value is the contents of etc/hostname, unquoted in the command
 * substitution and unescaped, so whitespace or a double-quote in the file
 * corrupts the output. Read-only.
 */
export const getHostnameOptions = (options?: Options<GetHostnameData>) => queryOptions<GetHostnameResponse, AxiosError<DefaultError>, GetHostnameResponse, ReturnType<typeof getHostnameQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHostname({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHostnameQueryKey(options)
});

export const getLinksQueryKey = (options?: Options<GetLinksData>) => createQueryKey('getLinks', options);

/**
 * Get RTSP stream and snapshot URLs
 *
 * Returns stream and snapshot URLs derived from system.conf. Read-only; all
 * query parameters are ignored.
 *
 * Which fields appear depends on config: the RTSP stream fields
 * (low_res_stream, high_res_stream, audio_stream) are only present when RTSP
 * is enabled and configured; audio_stream appears whenever RTSP_AUDIO is not
 * exactly `no` and not exactly `none` (so an unset value still yields it).
 * The two snapshot fields are always present. Note a port-suffix quirk: the
 * default HTTPD_PORT (8080) is compared against "80", so snapshot URLs get
 * `:8080` appended by default. Values are interpolated raw (no escaping).
 */
export const getLinksOptions = (options?: Options<GetLinksData>) => queryOptions<GetLinksResponse, AxiosError<DefaultError>, GetLinksResponse, ReturnType<typeof getLinksQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getLinks({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getLinksQueryKey(options)
});

export const testProxyQueryKey = (options: Options<TestProxyData>) => createQueryKey('testProxy', options);

/**
 * Test outbound connectivity (optionally via proxychains)
 *
 * Makes an outbound `wget http://ipinfo.io` and splices the raw response
 * into the `result` field. Only the FIRST query parameter is parsed and its
 * key MUST be literally `proxy`; if not (including an empty query string)
 * the response is `{"error":"true"}`.
 *
 * The value `1` routes the request through proxychains4; any other value
 * (0, 2, empty) is NOT an error - a direct wget runs and success is returned.
 * `result` is injected BARE/raw from ipinfo.io; if wget fails and the result
 * is empty the body becomes malformed JSON. The whole query string is also
 * gated by the validateQueryString blocklist.
 */
export const testProxyOptions = (options: Options<TestProxyData>) => queryOptions<TestProxyResponse, AxiosError<DefaultError>, TestProxyResponse, ReturnType<typeof testProxyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await testProxy({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: testProxyQueryKey(options)
});

export const getEventDirsQueryKey = (options?: Options<GetEventDirsData>) => createQueryKey('getEventDirs', options);

/**
 * List motion-event recording directories
 *
 * Lists recording directories under `/tmp/sd/record` whose name contains
 * `H` and is exactly 14 chars long (e.g. `2024Y08M24D15H`). Read-only; takes
 * no parameters (query string is never read).
 *
 * Known bug: the record COUNT counts every `H`-matching entry but only
 * 14-char entries are emitted, so a non-14-char entry leaves a dangling
 * trailing comma before `]}` -> malformed JSON. Parse defensively.
 */
export const getEventDirsOptions = (options?: Options<GetEventDirsData>) => queryOptions<GetEventDirsResponse, AxiosError<DefaultError>, GetEventDirsResponse, ReturnType<typeof getEventDirsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getEventDirs({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getEventDirsQueryKey(options)
});

export const getEventFilesQueryKey = (options: Options<GetEventFilesData>) => createQueryKey('getEventFiles', options);

/**
 * List recordings inside an event directory
 *
 * Lists the `.mp4` recordings inside one event directory. Read-only.
 *
 * The `dirname` value is only gated by the validateQueryString blocklist;
 * the intended 14-char Y/M/D/H format check is DEAD CODE (spaced assignment
 * bug), so the value is passed UNQUOTED into `ls -r /tmp/sd/record/$DIR` -
 * enabling directory traversal (e.g. `dirname=../..`). If dirname is missing
 * or the first key is not `dirname`, the response is `{"error":"true"}`. An
 * empty value (`dirname=`) is accepted and lists the record ROOT.
 *
 * Known bug: a mismatch between the mp4 COUNT and the emitted entries can
 * leave a dangling trailing comma -> malformed JSON.
 */
export const getEventFilesOptions = (options: Options<GetEventFilesData>) => queryOptions<GetEventFilesResponse, AxiosError<DefaultError>, GetEventFilesResponse, ReturnType<typeof getEventFilesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getEventFiles({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getEventFilesQueryKey(options)
});

export const deleteEventDirQueryKey = (options?: Options<DeleteEventDirData>) => createQueryKey('deleteEventDir', options);

/**
 * Delete an event directory (DESTRUCTIVE mutating GET)
 *
 * DESTRUCTIVE. Runs `rm -rf /tmp/sd/record/$DIR` with $DIR UNQUOTED. Despite
 * being GET this deletes data - never prefetch.
 *
 * The special value `dir=all` expands $DIR to the glob `*` and deletes ALL
 * recording directories. The 14-char format check is DEAD CODE, and the
 * blocklist permits `/`, `.`, and space, so path traversal / argument
 * splitting are possible.
 *
 * ALWAYS reports `{"error":"false"}` when the query-string gate passes -
 * even when `dir` is missing/misnamed and nothing was deleted. The response
 * cannot distinguish a successful delete from a no-op. A blocklisted char in
 * the query string returns `{"error":"true"}`.
 */
export const deleteEventDirOptions = (options?: Options<DeleteEventDirData>) => queryOptions<DeleteEventDirResponse, AxiosError<DefaultError>, DeleteEventDirResponse, ReturnType<typeof deleteEventDirQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await deleteEventDir({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: deleteEventDirQueryKey(options)
});

export const deleteEventFileQueryKey = (options: Options<DeleteEventFileData>) => createQueryKey('deleteEventFile', options);

/**
 * Delete one recording and its thumbnail (DESTRUCTIVE mutating GET)
 *
 * DESTRUCTIVE. Removes `<base>.mp4` and `<base>.jpg` (same base) from
 * /tmp/sd/record. Despite being GET this deletes data - never prefetch.
 *
 * The `file` value (a `<dirname>/<filename>` path) IS validated by a working
 * validateRecFile: length must be exactly 27 or 29, with marker chars `Y` at
 * index 4, `M` at 7, `D` at 10, `H` at 13, an `M` at index 17 or 19, and an
 * `S` at index 20 or 22. A missing/misnamed param or a format failure returns
 * `{"error":"true"}`. Success returns `{"error":"false"}` even if the files
 * did not exist (`rm -f` never fails).
 */
export const deleteEventFileOptions = (options: Options<DeleteEventFileData>) => queryOptions<DeleteEventFileResponse, AxiosError<DefaultError>, DeleteEventFileResponse, ReturnType<typeof deleteEventFileQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await deleteEventFile({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: deleteEventFileQueryKey(options)
});

export const getSnapshotQueryKey = (options?: Options<GetSnapshotData>) => createQueryKey('getSnapshot', options);

/**
 * Capture a JPEG snapshot
 *
 * Captures a snapshot via the imggrabber binary. The response content type
 * varies by parameters and all variants share HTTP 200:
 * - default: raw binary JPEG (`image/jpeg`).
 * - base64=yes: base64-encoded JPEG text under content type
 * `image/jpeg;base64` (note: the body is ASCII base64, not binary).
 * - a valid `file` param (resolving under /tmp/sd/record): writes the JPEG
 * to disk and returns JSON `{"error":"false"}`.
 * - a blocklisted query string: returns JSON `{"error":"true"}`.
 *
 * At most 4 query parameters are parsed (`for I in 1 2 3 4`); a 5th is
 * discarded. res/watermark/base64 use nested tests with NO else branch, so
 * out-of-domain values are silently dropped and the default is used. An
 * invalid `file` (fails validateBaseName or does not resolve under
 * /tmp/sd/record) is not an error - it falls through to the inline image.
 */
export const getSnapshotOptions = (options?: Options<GetSnapshotData>) => queryOptions<GetSnapshotResponse, AxiosError<DefaultError>, GetSnapshotResponse, ReturnType<typeof getSnapshotQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getSnapshot({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getSnapshotQueryKey(options)
});

export const startRecordingQueryKey = (options?: Options<StartRecordingData>) => createQueryKey('startRecording', options);

/**
 * Start an on-demand recording (mutating GET)
 *
 * Starts a recording of `time` seconds by running `ipc_cmd -S $TIME &`
 * (backgrounded, fire-and-forget). Despite being GET this changes device
 * state. Success JSON is emitted unconditionally, independent of whether
 * ipc_cmd actually succeeds.
 *
 * Only the FIRST query parameter is parsed (`for I in 1`), so `time` must be
 * first. `time` is validated by validateNumber (rejects empty or any char
 * outside `0-9 . , -`); a failure returns `{"error":"true"}`. Omitted -> 60.
 * No stock frontend caller.
 */
export const startRecordingOptions = (options?: Options<StartRecordingData>) => queryOptions<StartRecordingResponse, AxiosError<DefaultError>, StartRecordingResponse, ReturnType<typeof startRecordingQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await startRecording({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: startRecordingQueryKey(options)
});

export const getLastRecordedVideoQueryKey = (options?: Options<GetLastRecordedVideoData>) => createQueryKey('getLastRecordedVideo', options);

/**
 * Retrieve the most recent recording
 *
 * Returns the most recent recording in one of four forms selected by `type`.
 * All non-error variants share HTTP 200 with differing content types:
 * - type=1 (default) or any unrecognised type: `text/plain` relative path
 * `DIRNAME/VIDEO.mp4`.
 * - type=2: `text/plain` absolute URL
 * `http://LOCAL_IP:HTTPD_PORT/record/DIRNAME/VIDEO.mp4`.
 * - type=3: the raw mp4 (`video/mp4; charset=utf-8` - an unusual charset param
 * on binary mp4, `Content-Disposition: inline`).
 * - type=4: the raw mp4 (`video/mp4; charset=utf-8`, `Content-Disposition: attachment`).
 * - blocklisted query string: JSON `{"error":"true"}` (the ONLY JSON path).
 *
 * At most 2 query params are parsed (`for I in 1 2`). `oldness` and `type`
 * are NOT validated by validateNumber - only the whole-query blocklist
 * applies; a non-numeric `oldness` triggers a `[: bad number` runtime error
 * but the script continues on the default path.
 *
 * WARNING: `oldness < 0` makes the script WAIT for the next video, sleeping
 * 0.1s up to ~800 times - worst-case latency ~80 seconds. There is no JSON
 * success path; a missing video yields an empty body under an already-sent
 * video/mp4 header.
 */
export const getLastRecordedVideoOptions = (options?: Options<GetLastRecordedVideoData>) => queryOptions<GetLastRecordedVideoResponse, AxiosError<DefaultError>, GetLastRecordedVideoResponse, ReturnType<typeof getLastRecordedVideoQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getLastRecordedVideo({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getLastRecordedVideoQueryKey(options)
});

export const timelapseQueryKey = (options: Options<TimelapseData>) => createQueryKey('timelapse', options);

/**
 * List or delete timelapse videos
 *
 * Two modes selected by `action`:
 * - `action=list`: returns `{"error":"false","records":[...]}` of timelapse
 * `.avi` files.
 * - `action=delete`: requires a valid `file` (validateTLFile: length exactly
 * 23, `-` at indices 4,7,13,16, `_` at index 10, and `.avi` at 19-22; date
 * and time digits are NOT checked). Deletes the file and returns
 * `{"error":"false"}`; a missing/invalid file returns `{"error":"true"}`.
 *
 * WARNING: any other `action` (including the default `none`) produces a
 * COMPLETELY EMPTY response with NO Content-type header. Error paths use
 * `return` (not `exit`), which is a no-op at top level, so behavior after an
 * error can be unusual. At most 2 query params are parsed. The list path
 * shares the trailing-comma JSON bug (COUNT vs 23-char filter).
 */
export const timelapseOptions = (options: Options<TimelapseData>) => queryOptions<TimelapseResponse, AxiosError<DefaultError>, TimelapseResponse, ReturnType<typeof timelapseQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await timelapse({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: timelapseQueryKey(options)
});

export const ptzMoveQueryKey = (options?: Options<PtzMoveData>) => createQueryKey('ptzMove', options);

/**
 * Move the pan/tilt/zoom motor (mutating GET)
 *
 * Drives the PTZ motor via ipc_cmd. Despite being GET this physically moves
 * the lens. At most 5 query params are parsed (`for I in 1 2 3 4 5`).
 *
 * `action` (default `step`) selects the mode: `step` moves in `dir` for
 * `time` seconds then stops; `cont` moves in `dir` with no stop; `abs`/`rel`
 * move to/by `x,y`. An unknown action returns `{"error":"true"}`.
 *
 * `x`/`y`/`time` are validated by validateNumber and `dir` by validateString;
 * ANY validator failure returns `{"error":"true"}` even for a param the
 * chosen action never uses. `dir` is only charset-validated, never checked
 * against a movement enum, and is passed UNQUOTED to ipc_cmd; a `_` splits it
 * into two sequential moves (e.g. `up_left`). WARNING: `time` is an unbounded
 * client-controlled `sleep` (DoS risk).
 */
export const ptzMoveOptions = (options?: Options<PtzMoveData>) => queryOptions<PtzMoveResponse, AxiosError<DefaultError>, PtzMoveResponse, ReturnType<typeof ptzMoveQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ptzMove({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ptzMoveQueryKey(options)
});

export const ptzPresetQueryKey = (options: Options<PtzPresetData>) => createQueryKey('ptzPreset', options);

/**
 * Manage PTZ presets (mutating GET)
 *
 * Manages PTZ presets by invoking the external `ptz_presets.sh`. Despite
 * being GET, add/delete/go mutate presets and move the lens. At most 3 query
 * params are parsed.
 *
 * `action` is required. Stock values: `go_preset`, `add_preset`,
 * `del_preset`. `none` (the default) and `get_presets` are explicitly refused
 * with `{"error":"true","message":"-99"}` - presets are READ via
 * `getConfigs?conf=ptz_presets`, not here. `action` has no dedicated
 * per-parameter validator (the whole query string is still charset-filtered by
 * validateQueryString) and is passed UNQUOTED to the external script.
 *
 * `num` must satisfy validateNumber OR be the literal `all` (used by
 * delete-all); otherwise `{"error":"true","message":"Wrong arguments"}`.
 * `name` must satisfy validateString (rejects `. , & ( )` among others), so
 * free-text preset names with those chars are rejected. The stock UI POSTs
 * add/del but the script ignores the body and reads only the query string.
 */
export const ptzPresetOptions = (options: Options<PtzPresetData>) => queryOptions<PtzPresetResponse, AxiosError<DefaultError>, PtzPresetResponse, ReturnType<typeof ptzPresetQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ptzPreset({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ptzPresetQueryKey(options)
});

/**
 * Scan for Wi-Fi networks or save Wi-Fi credentials (mutating on save)
 *
 * ONE endpoint with two modes selected by the `action` query parameter. This
 * is modelled as a single POST operation because the `save` mode needs a
 * request body; note that in the firmware the `scan` mode is actually invoked
 * as a GET with no body. The response schema is a oneOf of the two shapes.
 *
 * - `action=scan`: returns `{"wifi":[...]}` - an array of ESSID strings,
 * ALWAYS terminated by an empty-string element `""` to absorb the trailing
 * comma. SSIDs are injected raw/unescaped and are not guaranteed valid JSON.
 * - `action=save` (mutating): reads a one-line JSON body with WIFI_ESSID,
 * WIFI_PASSWORD, WIFI_PASSWORD2. If the JSON is valid and WIFI_PASSWORD ==
 * WIFI_PASSWORD2, it writes the credentials, runs configure_wifi.sh (then
 * `sleep 1`) and returns `{"error":"false"}`; invalid JSON or a password
 * mismatch returns `{"error":"true"}`. Body values bypass all validators
 * (only JSON validity is enforced).
 *
 * Only the FIRST `=`-delimited pair is parsed for `action`, so `action` must
 * be the sole query parameter. Any action other than scan/save yields an
 * EMPTY response with no headers.
 */
export const wifiMutation = (options?: Partial<Options<WifiData>>): UseMutationOptions<WifiResponse, AxiosError<DefaultError>, Options<WifiData>> => {
    const mutationOptions: UseMutationOptions<WifiResponse, AxiosError<DefaultError>, Options<WifiData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await wifi({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Speak text through the camera speaker (text-to-speech)
 *
 * Synthesises the POST body text via nanotts and plays it through the
 * speaker. The body is read with `read -r` (first line only), is NOT
 * validated, and is echoed unescaped into the response `description` (a `"`
 * in the text breaks the JSON). Success path runs `sleep 1`.
 *
 * At most 2 query params are parsed. `lang` (default `en-US`) must pass
 * validateLang: exactly 5 chars matching `[A-Za-z-]` (so `en_US` and `en`
 * are rejected). Volume is set by either `vol` (linear, `pcmvol -g`) or
 * `voldb` (dB, `pcmvol -G`); whichever is processed LAST wins (order
 * matters). Both use validateNumber.
 *
 * Failure descriptions include "Invalid language", "Invalid volume",
 * "Invalid volume (dB)", "Speaker busy", "TTS engine not found",
 * "Audio input disabled". NOTE: the lang/vol/voldb validation-failure
 * branches emit the JSON body WITHOUT a Content-type header.
 */
export const speakTextMutation = (options?: Partial<Options<SpeakTextData>>): UseMutationOptions<SpeakTextResponse, AxiosError<DefaultError>, Options<SpeakTextData>> => {
    const mutationOptions: UseMutationOptions<SpeakTextResponse, AxiosError<DefaultError>, Options<SpeakTextData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await speakText({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Play an uploaded audio clip through the speaker
 *
 * Plays an uploaded audio payload (multipart form field, or a raw PCM/WAV
 * stream) through the speaker. If the data begins with a multipart boundary
 * the wrapper is stripped heuristically; a leading `RIFF` (WAV header) has
 * its first 4 bytes stripped. The body is not validated.
 *
 * Only the FIRST query param is parsed, so `vol` and `voldb` are mutually
 * exclusive (whichever comes first wins); both use validateNumber. If the SD
 * card is mounted, playback is BACKGROUNDED and success returns immediately
 * (with empty description); if not mounted, playback is synchronous and the
 * body must be <= 512000 bytes or the response is
 * `{"error":"true","description":"File is too big"}`. Missing
 * `/tmp/audio_in_fifo` returns "Audio input is not available". Worst-case
 * blocking `sleep 1`. NOTE: the vol/voldb validateNumber failure branches emit
 * the JSON body WITHOUT a Content-type header (only the query-string-blocklist
 * and later branches include it).
 */
export const playAudioMutation = (options?: Partial<Options<PlayAudioData>>): UseMutationOptions<PlayAudioResponse, AxiosError<DefaultError>, Options<PlayAudioData>> => {
    const mutationOptions: UseMutationOptions<PlayAudioResponse, AxiosError<DefaultError>, Options<PlayAudioData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await playAudio({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Play an existing audio file from /tmp/sd/audio
 *
 * Plays a pre-existing file from `/tmp/sd/audio/`. The POST body (first line
 * only) is the FILENAME. WARNING: the filename is NOT validated and is used
 * UNQUOTED, so path traversal (e.g. `../../etc/passwd`) is possible. Success
 * runs `sleep 1`. No stock frontend caller.
 *
 * Only `voldb` is honoured (always dB via `pcmvol -G`); there is no linear
 * option. KNOWN BUGS: the "File not found" and "Audio input disabled" JSON
 * bodies are MALFORMED (missing the comma between `error` and `description`).
 * Parse defensively. NOTE: the voldb validateNumber failure branch emits its
 * JSON body WITHOUT a Content-type header (the header is printed only after
 * that check).
 */
export const playAudioFileMutation = (options?: Partial<Options<PlayAudioFileData>>): UseMutationOptions<PlayAudioFileResponse, AxiosError<DefaultError>, Options<PlayAudioFileData>> => {
    const mutationOptions: UseMutationOptions<PlayAudioFileResponse, AxiosError<DefaultError>, Options<PlayAudioFileData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await playAudioFile({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const firmwareUpgradeQueryKey = (options: Options<FirmwareUpgradeData>) => createQueryKey('firmwareUpgrade', options);

/**
 * Query firmware version or trigger a firmware upgrade (mutating GET)
 *
 * Two modes selected by the required `get` parameter (which must be the sole
 * query param - the script does `cut -d'='` on the whole string).
 *
 * - `get=info`: returns JSON with fw_version, latest_fw (from a LIVE wget to
 * the GitHub API - empty string if the network call fails), and `local_fw`
 * as a BARE JSON boolean (the one place the API emits a real boolean).
 * - `get=upgrade` (DESTRUCTIVE, mutating): returns `text/html` plain text on
 * all sub-paths (e.g. "No SD detected.", "No space left on SD.", "No new
 * firmware available.", "Unable to download firmware file.", "Download
 * completed, rebooting and upgrading."). It runs `rm -rf` on four /tmp/sd
 * paths BEFORE checking whether the download will succeed, then reboots.
 *
 * A blocklisted query string returns JSON `{"error":"true"}`. A missing/
 * wrong `get` key, or a value outside {info,upgrade}, returns an EMPTY body
 * with no Content-type header.
 */
export const firmwareUpgradeOptions = (options: Options<FirmwareUpgradeData>) => queryOptions<FirmwareUpgradeResponse, AxiosError<DefaultError>, FirmwareUpgradeResponse, ReturnType<typeof firmwareUpgradeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await firmwareUpgrade({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: firmwareUpgradeQueryKey(options)
});

export const rebootQueryKey = (options?: Options<RebootData>) => createQueryKey('reboot', options);

/**
 * Reboot the camera (DESTRUCTIVE mutating GET)
 *
 * Reboots the camera. Takes no parameters and performs no validation. Returns
 * `{"error":"false"}` FIRST, then runs `sync` x3, `killall mqttv4`,
 * `sleep 1`, and `reboot`. Despite being GET this reboots the device - never
 * prefetch or crawl.
 */
export const rebootOptions = (options?: Options<RebootData>) => queryOptions<RebootResponse, AxiosError<DefaultError>, RebootResponse, ReturnType<typeof rebootQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await reboot({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: rebootQueryKey(options)
});

export const resetConfigQueryKey = (options?: Options<ResetConfigData>) => createQueryKey('resetConfig', options);

/**
 * Factory-reset the configuration (DESTRUCTIVE mutating GET)
 *
 * Restores factory configuration: deletes hostname and the camera/mqttv4/
 * proxychains/system conf files, then extracts `defaults.tar.bz2`. Takes no
 * parameters and no validation. Does NOT reboot (the UI tells the user to
 * reboot manually). Returns `{"error":"false"}` unconditionally AFTER the
 * destructive ops, so a failed delete/extract still reports success. Despite
 * being GET this wipes config - never prefetch or crawl.
 */
export const resetConfigOptions = (options?: Options<ResetConfigData>) => queryOptions<ResetConfigResponse, AxiosError<DefaultError>, ResetConfigResponse, ReturnType<typeof resetConfigQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await resetConfig({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: resetConfigQueryKey(options)
});

export const saveConfigQueryKey = (options?: Options<SaveConfigData>) => createQueryKey('saveConfig', options);

/**
 * Download a config backup archive
 *
 * Returns a bzip2-compressed tar (config.tar.bz2) of all etc*.conf plus
 * hostname. Read-only. Body is raw binary (application/octet-stream); the
 * stock UI downloads it as a blob named config.tar.bz2.
 */
export const saveConfigOptions = (options?: Options<SaveConfigData>) => queryOptions<SaveConfigResponse, AxiosError<DefaultError>, SaveConfigResponse, ReturnType<typeof saveConfigQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await saveConfig({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: saveConfigQueryKey(options)
});

/**
 * Upload and restore a config backup archive (mutating)
 *
 * Restores configuration from an uploaded `config.tar.bz2` (multipart field
 * `files[]`). The archive MUST contain both system.conf and camera.conf.
 * CONTENT_LENGTH must be <= 10000 bytes, or the script silently exits with an
 * EMPTY body and no Content-type header.
 *
 * On success returns `text/html` "Upload completed successfully, restart your
 * camera"; on failure "Upload failed". AFTER sending the response it applies
 * live camera settings via ipc_cmd (worst-case `sleep 0.5` when CRUISE is
 * presets/360). No validator is sourced; trust rests on the multipart parse
 * and tar.
 */
export const loadConfigMutation = (options?: Partial<Options<LoadConfigData>>): UseMutationOptions<LoadConfigResponse, AxiosError<DefaultError>, Options<LoadConfigData>> => {
    const mutationOptions: UseMutationOptions<LoadConfigResponse, AxiosError<DefaultError>, Options<LoadConfigData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await loadConfig({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const controlServiceQueryKey = (options?: Options<ControlServiceData>) => createQueryKey('controlService', options);

/**
 * Start/stop/query a camera service (mutating for start/stop)
 *
 * Starts, stops, or queries a camera service by invoking the external
 * service.sh. At most 4 query params are parsed. No stock frontend caller.
 *
 * - `action=status` with a matched `name` returns `{"status":"<RES>"}`, where
 * RES (backend stdout) is injected RAW into the printf format string (not
 * JSON-escaped). `all` is NOT a valid name for status.
 * - `action=start` / `action=stop` (and every unmatched name/action) return
 * `{}` - an empty object with no error and no status, so the client cannot
 * tell success from a typo.
 * - A blocklisted query string returns `{"error":"true"}`.
 *
 * `param1`/`param2` default to the literal string `none` and are forwarded
 * positionally (unquoted) to the backend for rtsp/onvif/ftpd starts.
 */
export const controlServiceOptions = (options?: Options<ControlServiceData>) => queryOptions<ControlServiceResponse, AxiosError<DefaultError>, ControlServiceResponse, ReturnType<typeof controlServiceQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await controlService({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: controlServiceQueryKey(options)
});
