// Extracted verbatim from the stock UI lookup table
// (src/www/httpd/htdocs/pages/tz.html) — the stock tz page is this table and
// nothing else. Location names keep the stock spelling (spaces, not
// underscores as IANA uses).
export type TimezoneEntry = {
	location: string;
	tz: string;
};

export const TIMEZONES: readonly TimezoneEntry[] = [
	{ location: "Africa/Abidjan", tz: "GMT0" },
	{ location: "Africa/Accra", tz: "GMT0" },
	{ location: "Africa/Addis Ababa", tz: "EAT-3" },
	{ location: "Africa/Algiers", tz: "CET-1" },
	{ location: "Africa/Asmara", tz: "EAT-3" },
	{ location: "Africa/Bamako", tz: "GMT0" },
	{ location: "Africa/Bangui", tz: "WAT-1" },
	{ location: "Africa/Banjul", tz: "GMT0" },
	{ location: "Africa/Bissau", tz: "GMT0" },
	{ location: "Africa/Blantyre", tz: "CAT-2" },
	{ location: "Africa/Brazzaville", tz: "WAT-1" },
	{ location: "Africa/Bujumbura", tz: "CAT-2" },
	{ location: "Africa/Casablanca", tz: "WET0" },
	{ location: "Africa/Ceuta", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Africa/Conakry", tz: "GMT0" },
	{ location: "Africa/Dakar", tz: "GMT0" },
	{ location: "Africa/Dar es Salaam", tz: "EAT-3" },
	{ location: "Africa/Djibouti", tz: "EAT-3" },
	{ location: "Africa/Douala", tz: "WAT-1" },
	{ location: "Africa/El Aaiun", tz: "WET0" },
	{ location: "Africa/Freetown", tz: "GMT0" },
	{ location: "Africa/Gaborone", tz: "CAT-2" },
	{ location: "Africa/Harare", tz: "CAT-2" },
	{ location: "Africa/Johannesburg", tz: "SAST-2" },
	{ location: "Africa/Kampala", tz: "EAT-3" },
	{ location: "Africa/Khartoum", tz: "EAT-3" },
	{ location: "Africa/Kigali", tz: "CAT-2" },
	{ location: "Africa/Kinshasa", tz: "WAT-1" },
	{ location: "Africa/Lagos", tz: "WAT-1" },
	{ location: "Africa/Libreville", tz: "WAT-1" },
	{ location: "Africa/Lome", tz: "GMT0" },
	{ location: "Africa/Luanda", tz: "WAT-1" },
	{ location: "Africa/Lubumbashi", tz: "CAT-2" },
	{ location: "Africa/Lusaka", tz: "CAT-2" },
	{ location: "Africa/Malabo", tz: "WAT-1" },
	{ location: "Africa/Maputo", tz: "CAT-2" },
	{ location: "Africa/Maseru", tz: "SAST-2" },
	{ location: "Africa/Mbabane", tz: "SAST-2" },
	{ location: "Africa/Mogadishu", tz: "EAT-3" },
	{ location: "Africa/Monrovia", tz: "GMT0" },
	{ location: "Africa/Nairobi", tz: "EAT-3" },
	{ location: "Africa/Ndjamena", tz: "WAT-1" },
	{ location: "Africa/Niamey", tz: "WAT-1" },
	{ location: "Africa/Nouakchott", tz: "GMT0" },
	{ location: "Africa/Ouagadougou", tz: "GMT0" },
	{ location: "Africa/Porto-Novo", tz: "WAT-1" },
	{ location: "Africa/Sao Tome", tz: "GMT0" },
	{ location: "Africa/Tripoli", tz: "EET-2" },
	{ location: "Africa/Tunis", tz: "CET-1" },
	{ location: "Africa/Windhoek", tz: "WAT-1WAST,M9.1.0,M4.1.0" },
	{ location: "America/Adak", tz: "HAST10HADT,M3.2.0,M11.1.0" },
	{ location: "America/Anchorage", tz: "AKST9AKDT,M3.2.0,M11.1.0" },
	{ location: "America/Anguilla", tz: "AST4" },
	{ location: "America/Antigua", tz: "AST4" },
	{ location: "America/Araguaina", tz: "BRT3" },
	{ location: "America/Argentina/Buenos Aires", tz: "ART3" },
	{ location: "America/Argentina/Catamarca", tz: "ART3" },
	{ location: "America/Argentina/Cordoba", tz: "ART3" },
	{ location: "America/Argentina/Jujuy", tz: "ART3" },
	{ location: "America/Argentina/La Rioja", tz: "ART3" },
	{ location: "America/Argentina/Mendoza", tz: "ART3" },
	{ location: "America/Argentina/Rio Gallegos", tz: "ART3" },
	{ location: "America/Argentina/Salta", tz: "ART3" },
	{ location: "America/Argentina/San Juan", tz: "ART3" },
	{ location: "America/Argentina/Tucuman", tz: "ART3" },
	{ location: "America/Argentina/Ushuaia", tz: "ART3" },
	{ location: "America/Aruba", tz: "AST4" },
	{ location: "America/Asuncion", tz: "PYT4PYST,M10.1.0/0,M4.2.0/0" },
	{ location: "America/Atikokan", tz: "EST5" },
	{ location: "America/Bahia", tz: "BRT3" },
	{ location: "America/Barbados", tz: "AST4" },
	{ location: "America/Belem", tz: "BRT3" },
	{ location: "America/Belize", tz: "CST6" },
	{ location: "America/Blanc-Sablon", tz: "AST4" },
	{ location: "America/Boa Vista", tz: "AMT4" },
	{ location: "America/Bogota", tz: "COT5" },
	{ location: "America/Boise", tz: "MST7MDT,M3.2.0,M11.1.0" },
	{ location: "America/Cambridge Bay", tz: "MST7MDT,M3.2.0,M11.1.0" },
	{ location: "America/Campo Grande", tz: "AMT4" },
	{ location: "America/Cancun", tz: "CST6CDT,M4.1.0,M10.5.0" },
	{ location: "America/Caracas", tz: "VET4:30" },
	{ location: "America/Cayenne", tz: "GFT3" },
	{ location: "America/Cayman", tz: "EST5" },
	{ location: "America/Chicago", tz: "CST6CDT,M3.2.0,M11.1.0" },
	{ location: "America/Chihuahua", tz: "MST7MDT,M4.1.0,M10.5.0" },
	{ location: "America/Costa Rica", tz: "CST6" },
	{ location: "America/Cuiaba", tz: "AMT4" },
	{ location: "America/Curacao", tz: "AST4" },
	{ location: "America/Danmarkshavn", tz: "GMT0" },
	{ location: "America/Dawson", tz: "PST8PDT,M3.2.0,M11.1.0" },
	{ location: "America/Dawson Creek", tz: "MST7" },
	{ location: "America/Denver", tz: "MST7MDT,M3.2.0,M11.1.0" },
	{ location: "America/Detroit", tz: "EST5EDT,M3.2.0,M11.1.0" },
	{ location: "America/Dominica", tz: "AST4" },
	{ location: "America/Edmonton", tz: "MST7MDT,M3.2.0,M11.1.0" },
	{ location: "America/Eirunepe", tz: "ACT5" },
	{ location: "America/El Salvador", tz: "CST6" },
	{ location: "America/Fortaleza", tz: "BRT3" },
	{ location: "America/Glace Bay", tz: "AST4ADT,M3.2.0,M11.1.0" },
	{ location: "America/Goose Bay", tz: "AST4ADT,M3.2.0/0:01,M11.1.0/0:01" },
	{ location: "America/Grand Turk", tz: "EST5EDT,M3.2.0,M11.1.0" },
	{ location: "America/Grenada", tz: "AST4" },
	{ location: "America/Guadeloupe", tz: "AST4" },
	{ location: "America/Guatemala", tz: "CST6" },
	{ location: "America/Guayaquil", tz: "ECT5" },
	{ location: "America/Guyana", tz: "GYT4" },
	{ location: "America/Halifax", tz: "AST4ADT,M3.2.0,M11.1.0" },
	{ location: "America/Havana", tz: "CST5CDT,M3.2.0/0,M10.5.0/1" },
	{ location: "America/Hermosillo", tz: "MST7" },
	{ location: "America/Indiana/Indianapolis", tz: "EST5EDT,M3.2.0,M11.1.0" },
	{ location: "America/Indiana/Knox", tz: "CST6CDT,M3.2.0,M11.1.0" },
	{ location: "America/Indiana/Marengo", tz: "EST5EDT,M3.2.0,M11.1.0" },
	{ location: "America/Indiana/Petersburg", tz: "EST5EDT,M3.2.0,M11.1.0" },
	{ location: "America/Indiana/Tell City", tz: "CST6CDT,M3.2.0,M11.1.0" },
	{ location: "America/Indiana/Vevay", tz: "EST5EDT,M3.2.0,M11.1.0" },
	{ location: "America/Indiana/Vincennes", tz: "EST5EDT,M3.2.0,M11.1.0" },
	{ location: "America/Indiana/Winamac", tz: "EST5EDT,M3.2.0,M11.1.0" },
	{ location: "America/Inuvik", tz: "MST7MDT,M3.2.0,M11.1.0" },
	{ location: "America/Iqaluit", tz: "EST5EDT,M3.2.0,M11.1.0" },
	{ location: "America/Jamaica", tz: "EST5" },
	{ location: "America/Juneau", tz: "AKST9AKDT,M3.2.0,M11.1.0" },
	{ location: "America/Kentucky/Louisville", tz: "EST5EDT,M3.2.0,M11.1.0" },
	{ location: "America/Kentucky/Monticello", tz: "EST5EDT,M3.2.0,M11.1.0" },
	{ location: "America/La Paz", tz: "BOT4" },
	{ location: "America/Lima", tz: "PET5" },
	{ location: "America/Los Angeles", tz: "PST8PDT,M3.2.0,M11.1.0" },
	{ location: "America/Maceio", tz: "BRT3" },
	{ location: "America/Managua", tz: "CST6" },
	{ location: "America/Manaus", tz: "AMT4" },
	{ location: "America/Marigot", tz: "AST4" },
	{ location: "America/Martinique", tz: "AST4" },
	{ location: "America/Matamoros", tz: "CST6CDT,M3.2.0,M11.1.0" },
	{ location: "America/Mazatlan", tz: "MST7MDT,M4.1.0,M10.5.0" },
	{ location: "America/Menominee", tz: "CST6CDT,M3.2.0,M11.1.0" },
	{ location: "America/Merida", tz: "CST6CDT,M4.1.0,M10.5.0" },
	{ location: "America/Mexico City", tz: "CST6CDT,M4.1.0,M10.5.0" },
	{ location: "America/Miquelon", tz: "PMST3PMDT,M3.2.0,M11.1.0" },
	{ location: "America/Moncton", tz: "AST4ADT,M3.2.0,M11.1.0" },
	{ location: "America/Monterrey", tz: "CST6CDT,M4.1.0,M10.5.0" },
	{ location: "America/Montevideo", tz: "UYT3UYST,M10.1.0,M3.2.0" },
	{ location: "America/Montreal", tz: "EST5EDT,M3.2.0,M11.1.0" },
	{ location: "America/Montserrat", tz: "AST4" },
	{ location: "America/Nassau", tz: "EST5EDT,M3.2.0,M11.1.0" },
	{ location: "America/New York", tz: "EST5EDT,M3.2.0,M11.1.0" },
	{ location: "America/Nipigon", tz: "EST5EDT,M3.2.0,M11.1.0" },
	{ location: "America/Nome", tz: "AKST9AKDT,M3.2.0,M11.1.0" },
	{ location: "America/Noronha", tz: "FNT2" },
	{ location: "America/North Dakota/Center", tz: "CST6CDT,M3.2.0,M11.1.0" },
	{ location: "America/North Dakota/New Salem", tz: "CST6CDT,M3.2.0,M11.1.0" },
	{ location: "America/Ojinaga", tz: "MST7MDT,M3.2.0,M11.1.0" },
	{ location: "America/Panama", tz: "EST5" },
	{ location: "America/Pangnirtung", tz: "EST5EDT,M3.2.0,M11.1.0" },
	{ location: "America/Paramaribo", tz: "SRT3" },
	{ location: "America/Phoenix", tz: "MST7" },
	{ location: "America/Port of Spain", tz: "AST4" },
	{ location: "America/Port-au-Prince", tz: "EST5" },
	{ location: "America/Porto Velho", tz: "AMT4" },
	{ location: "America/Puerto Rico", tz: "AST4" },
	{ location: "America/Rainy River", tz: "CST6CDT,M3.2.0,M11.1.0" },
	{ location: "America/Rankin Inlet", tz: "CST6CDT,M3.2.0,M11.1.0" },
	{ location: "America/Recife", tz: "BRT3" },
	{ location: "America/Regina", tz: "CST6" },
	{ location: "America/Rio Branco", tz: "ACT5" },
	{ location: "America/Santa Isabel", tz: "PST8PDT,M4.1.0,M10.5.0" },
	{ location: "America/Santarem", tz: "BRT3" },
	{ location: "America/Santo Domingo", tz: "AST4" },
	{ location: "America/Sao Paulo", tz: "BRT3" },
	{ location: "America/Scoresbysund", tz: "EGT1EGST,M3.5.0/0,M10.5.0/1" },
	{ location: "America/Shiprock", tz: "MST7MDT,M3.2.0,M11.1.0" },
	{ location: "America/St Barthelemy", tz: "AST4" },
	{ location: "America/St Johns", tz: "NST3:30NDT,M3.2.0/0:01,M11.1.0/0:01" },
	{ location: "America/St Kitts", tz: "AST4" },
	{ location: "America/St Lucia", tz: "AST4" },
	{ location: "America/St Thomas", tz: "AST4" },
	{ location: "America/St Vincent", tz: "AST4" },
	{ location: "America/Swift Current", tz: "CST6" },
	{ location: "America/Tegucigalpa", tz: "CST6" },
	{ location: "America/Thule", tz: "AST4ADT,M3.2.0,M11.1.0" },
	{ location: "America/Thunder Bay", tz: "EST5EDT,M3.2.0,M11.1.0" },
	{ location: "America/Tijuana", tz: "PST8PDT,M3.2.0,M11.1.0" },
	{ location: "America/Toronto", tz: "EST5EDT,M3.2.0,M11.1.0" },
	{ location: "America/Tortola", tz: "AST4" },
	{ location: "America/Vancouver", tz: "PST8PDT,M3.2.0,M11.1.0" },
	{ location: "America/Whitehorse", tz: "PST8PDT,M3.2.0,M11.1.0" },
	{ location: "America/Winnipeg", tz: "CST6CDT,M3.2.0,M11.1.0" },
	{ location: "America/Yakutat", tz: "AKST9AKDT,M3.2.0,M11.1.0" },
	{ location: "America/Yellowknife", tz: "MST7MDT,M3.2.0,M11.1.0" },
	{ location: "Antarctica/Casey", tz: "WST-8" },
	{ location: "Antarctica/Davis", tz: "DAVT-7" },
	{ location: "Antarctica/DumontDUrville", tz: "DDUT-10" },
	{ location: "Antarctica/Macquarie", tz: "MIST-11" },
	{ location: "Antarctica/Mawson", tz: "MAWT-5" },
	{ location: "Antarctica/McMurdo", tz: "NZST-12NZDT,M9.5.0,M4.1.0/3" },
	{ location: "Antarctica/Rothera", tz: "ROTT3" },
	{ location: "Antarctica/South Pole", tz: "NZST-12NZDT,M9.5.0,M4.1.0/3" },
	{ location: "Antarctica/Syowa", tz: "SYOT-3" },
	{ location: "Antarctica/Vostok", tz: "VOST-6" },
	{ location: "Arctic/Longyearbyen", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Asia/Aden", tz: "AST-3" },
	{ location: "Asia/Almaty", tz: "ALMT-6" },
	{ location: "Asia/Anadyr", tz: "ANAT-11ANAST,M3.5.0,M10.5.0/3" },
	{ location: "Asia/Aqtau", tz: "AQTT-5" },
	{ location: "Asia/Aqtobe", tz: "AQTT-5" },
	{ location: "Asia/Ashgabat", tz: "TMT-5" },
	{ location: "Asia/Baghdad", tz: "AST-3" },
	{ location: "Asia/Bahrain", tz: "AST-3" },
	{ location: "Asia/Baku", tz: "AZT-4AZST,M3.5.0/4,M10.5.0/5" },
	{ location: "Asia/Bangkok", tz: "ICT-7" },
	{ location: "Asia/Beirut", tz: "EET-2EEST,M3.5.0/0,M10.5.0/0" },
	{ location: "Asia/Bishkek", tz: "KGT-6" },
	{ location: "Asia/Brunei", tz: "BNT-8" },
	{ location: "Asia/Choibalsan", tz: "CHOT-8" },
	{ location: "Asia/Chongqing", tz: "CST-8" },
	{ location: "Asia/Colombo", tz: "IST-5:30" },
	{ location: "Asia/Damascus", tz: "EET-2EEST,M4.1.5/0,M10.5.5/0" },
	{ location: "Asia/Dhaka", tz: "BDT-6" },
	{ location: "Asia/Dili", tz: "TLT-9" },
	{ location: "Asia/Dubai", tz: "GST-4" },
	{ location: "Asia/Dushanbe", tz: "TJT-5" },
	{ location: "Asia/Gaza", tz: "EET-2EEST,M3.5.6/0:01,M9.1.5" },
	{ location: "Asia/Harbin", tz: "CST-8" },
	{ location: "Asia/Ho Chi Minh", tz: "ICT-7" },
	{ location: "Asia/Hong Kong", tz: "HKT-8" },
	{ location: "Asia/Hovd", tz: "HOVT-7" },
	{ location: "Asia/Irkutsk", tz: "IRKT-8IRKST,M3.5.0,M10.5.0/3" },
	{ location: "Asia/Jakarta", tz: "WIT-7" },
	{ location: "Asia/Jayapura", tz: "EIT-9" },
	{ location: "Asia/Kabul", tz: "AFT-4:30" },
	{ location: "Asia/Kamchatka", tz: "PETT-11PETST,M3.5.0,M10.5.0/3" },
	{ location: "Asia/Karachi", tz: "PKT-5" },
	{ location: "Asia/Kashgar", tz: "CST-8" },
	{ location: "Asia/Kathmandu", tz: "NPT-5:45" },
	{ location: "Asia/Kolkata", tz: "IST-5:30" },
	{ location: "Asia/Krasnoyarsk", tz: "KRAT-7KRAST,M3.5.0,M10.5.0/3" },
	{ location: "Asia/Kuala Lumpur", tz: "MYT-8" },
	{ location: "Asia/Kuching", tz: "MYT-8" },
	{ location: "Asia/Kuwait", tz: "AST-3" },
	{ location: "Asia/Macau", tz: "CST-8" },
	{ location: "Asia/Magadan", tz: "MAGT-11MAGST,M3.5.0,M10.5.0/3" },
	{ location: "Asia/Makassar", tz: "CIT-8" },
	{ location: "Asia/Manila", tz: "PHT-8" },
	{ location: "Asia/Muscat", tz: "GST-4" },
	{ location: "Asia/Nicosia", tz: "EET-2EEST,M3.5.0/3,M10.5.0/4" },
	{ location: "Asia/Novokuznetsk", tz: "NOVT-6NOVST,M3.5.0,M10.5.0/3" },
	{ location: "Asia/Novosibirsk", tz: "NOVT-6NOVST,M3.5.0,M10.5.0/3" },
	{ location: "Asia/Omsk", tz: "OMST-7" },
	{ location: "Asia/Oral", tz: "ORAT-5" },
	{ location: "Asia/Phnom Penh", tz: "ICT-7" },
	{ location: "Asia/Pontianak", tz: "WIT-7" },
	{ location: "Asia/Pyongyang", tz: "KST-9" },
	{ location: "Asia/Qatar", tz: "AST-3" },
	{ location: "Asia/Qyzylorda", tz: "QYZT-6" },
	{ location: "Asia/Rangoon", tz: "MMT-6:30" },
	{ location: "Asia/Riyadh", tz: "AST-3" },
	{ location: "Asia/Sakhalin", tz: "SAKT-10SAKST,M3.5.0,M10.5.0/3" },
	{ location: "Asia/Samarkand", tz: "UZT-5" },
	{ location: "Asia/Seoul", tz: "KST-9" },
	{ location: "Asia/Shanghai", tz: "CST-8" },
	{ location: "Asia/Singapore", tz: "SGT-8" },
	{ location: "Asia/Taipei", tz: "CST-8" },
	{ location: "Asia/Tashkent", tz: "UZT-5" },
	{ location: "Asia/Tbilisi", tz: "GET-4" },
	{ location: "Asia/Tehran", tz: "IRST-3:30IRDT,80/0,264/0" },
	{ location: "Asia/Thimphu", tz: "BTT-6" },
	{ location: "Asia/Tokyo", tz: "JST-9" },
	{ location: "Asia/Ulaanbaatar", tz: "ULAT-8" },
	{ location: "Asia/Urumqi", tz: "CST-8" },
	{ location: "Asia/Vientiane", tz: "ICT-7" },
	{ location: "Asia/Vladivostok", tz: "VLAT-10VLAST,M3.5.0,M10.5.0/3" },
	{ location: "Asia/Yakutsk", tz: "YAKT-9YAKST,M3.5.0,M10.5.0/3" },
	{ location: "Asia/Yekaterinburg", tz: "YEKT-5YEKST,M3.5.0,M10.5.0/3" },
	{ location: "Asia/Yerevan", tz: "AMT-4AMST,M3.5.0,M10.5.0/3" },
	{ location: "Atlantic/Azores", tz: "AZOT1AZOST,M3.5.0/0,M10.5.0/1" },
	{ location: "Atlantic/Bermuda", tz: "AST4ADT,M3.2.0,M11.1.0" },
	{ location: "Atlantic/Canary", tz: "WET0WEST,M3.5.0/1,M10.5.0" },
	{ location: "Atlantic/Cape Verde", tz: "CVT1" },
	{ location: "Atlantic/Faroe", tz: "WET0WEST,M3.5.0/1,M10.5.0" },
	{ location: "Atlantic/Madeira", tz: "WET0WEST,M3.5.0/1,M10.5.0" },
	{ location: "Atlantic/Reykjavik", tz: "GMT0" },
	{ location: "Atlantic/South Georgia", tz: "GST2" },
	{ location: "Atlantic/St Helena", tz: "GMT0" },
	{ location: "Atlantic/Stanley", tz: "FKT4FKST,M9.1.0,M4.3.0" },
	{ location: "Australia/Adelaide", tz: "CST-9:30CST,M10.1.0,M4.1.0/3" },
	{ location: "Australia/Brisbane", tz: "EST-10" },
	{ location: "Australia/Broken Hill", tz: "CST-9:30CST,M10.1.0,M4.1.0/3" },
	{ location: "Australia/Currie", tz: "EST-10EST,M10.1.0,M4.1.0/3" },
	{ location: "Australia/Darwin", tz: "CST-9:30" },
	{ location: "Australia/Eucla", tz: "CWST-8:45" },
	{ location: "Australia/Hobart", tz: "EST-10EST,M10.1.0,M4.1.0/3" },
	{ location: "Australia/Lindeman", tz: "EST-10" },
	{ location: "Australia/Lord Howe", tz: "LHST-10:30LHST-11,M10.1.0,M4.1.0" },
	{ location: "Australia/Melbourne", tz: "EST-10EST,M10.1.0,M4.1.0/3" },
	{ location: "Australia/Perth", tz: "WST-8" },
	{ location: "Australia/Sydney", tz: "EST-10EST,M10.1.0,M4.1.0/3" },
	{ location: "Europe/Amsterdam", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Andorra", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Athens", tz: "EET-2EEST,M3.5.0/3,M10.5.0/4" },
	{ location: "Europe/Belgrade", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Berlin", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Bratislava", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Brussels", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Bucharest", tz: "EET-2EEST,M3.5.0/3,M10.5.0/4" },
	{ location: "Europe/Budapest", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Chisinau", tz: "EET-2EEST,M3.5.0/3,M10.5.0/4" },
	{ location: "Europe/Copenhagen", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Dublin", tz: "GMT0IST,M3.5.0/1,M10.5.0" },
	{ location: "Europe/Gibraltar", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Guernsey", tz: "GMT0BST,M3.5.0/1,M10.5.0" },
	{ location: "Europe/Helsinki", tz: "EET-2EEST,M3.5.0/3,M10.5.0/4" },
	{ location: "Europe/Isle of Man", tz: "GMT0BST,M3.5.0/1,M10.5.0" },
	{ location: "Europe/Istanbul", tz: "EET-2EEST,M3.5.0/3,M10.5.0/4" },
	{ location: "Europe/Jersey", tz: "GMT0BST,M3.5.0/1,M10.5.0" },
	{ location: "Europe/Kaliningrad", tz: "EET-2EEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Kiev", tz: "EET-2EEST,M3.5.0/3,M10.5.0/4" },
	{ location: "Europe/Lisbon", tz: "WET0WEST,M3.5.0/1,M10.5.0" },
	{ location: "Europe/Ljubljana", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/London", tz: "GMT0BST,M3.5.0/1,M10.5.0" },
	{ location: "Europe/Luxembourg", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Madrid", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Malta", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Mariehamn", tz: "EET-2EEST,M3.5.0/3,M10.5.0/4" },
	{ location: "Europe/Minsk", tz: "EET-2EEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Monaco", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Moscow", tz: "MSK-3" },
	{ location: "Europe/Oslo", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Paris", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Podgorica", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Prague", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Riga", tz: "EET-2EEST,M3.5.0/3,M10.5.0/4" },
	{ location: "Europe/Rome", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Samara", tz: "SAMT-3SAMST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/San Marino", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Sarajevo", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Simferopol", tz: "EET-2EEST,M3.5.0/3,M10.5.0/4" },
	{ location: "Europe/Skopje", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Sofia", tz: "EET-2EEST,M3.5.0/3,M10.5.0/4" },
	{ location: "Europe/Stockholm", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Tallinn", tz: "EET-2EEST,M3.5.0/3,M10.5.0/4" },
	{ location: "Europe/Tirane", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Uzhgorod", tz: "EET-2EEST,M3.5.0/3,M10.5.0/4" },
	{ location: "Europe/Vaduz", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Vatican", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Vienna", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Vilnius", tz: "EET-2EEST,M3.5.0/3,M10.5.0/4" },
	{ location: "Europe/Volgograd", tz: "VOLT-3VOLST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Warsaw", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Zagreb", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Europe/Zaporozhye", tz: "EET-2EEST,M3.5.0/3,M10.5.0/4" },
	{ location: "Europe/Zurich", tz: "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ location: "Indian/Antananarivo", tz: "EAT-3" },
	{ location: "Indian/Chagos", tz: "IOT-6" },
	{ location: "Indian/Christmas", tz: "CXT-7" },
	{ location: "Indian/Cocos", tz: "CCT-6:30" },
	{ location: "Indian/Comoro", tz: "EAT-3" },
	{ location: "Indian/Kerguelen", tz: "TFT-5" },
	{ location: "Indian/Mahe", tz: "SCT-4" },
	{ location: "Indian/Maldives", tz: "MVT-5" },
	{ location: "Indian/Mauritius", tz: "MUT-4" },
	{ location: "Indian/Mayotte", tz: "EAT-3" },
	{ location: "Indian/Reunion", tz: "RET-4" },
	{ location: "Pacific/Apia", tz: "WST11" },
	{ location: "Pacific/Auckland", tz: "NZST-12NZDT,M9.5.0,M4.1.0/3" },
	{
		location: "Pacific/Chatham",
		tz: "CHAST-12:45CHADT,M9.5.0/2:45,M4.1.0/3:45",
	},
	{ location: "Pacific/Efate", tz: "VUT-11" },
	{ location: "Pacific/Enderbury", tz: "PHOT-13" },
	{ location: "Pacific/Fakaofo", tz: "TKT10" },
	{ location: "Pacific/Fiji", tz: "FJT-12" },
	{ location: "Pacific/Funafuti", tz: "TVT-12" },
	{ location: "Pacific/Galapagos", tz: "GALT6" },
	{ location: "Pacific/Gambier", tz: "GAMT9" },
	{ location: "Pacific/Guadalcanal", tz: "SBT-11" },
	{ location: "Pacific/Guam", tz: "ChST-10" },
	{ location: "Pacific/Honolulu", tz: "HST10" },
	{ location: "Pacific/Johnston", tz: "HST10" },
	{ location: "Pacific/Kiritimati", tz: "LINT-14" },
	{ location: "Pacific/Kosrae", tz: "KOST-11" },
	{ location: "Pacific/Kwajalein", tz: "MHT-12" },
	{ location: "Pacific/Majuro", tz: "MHT-12" },
	{ location: "Pacific/Marquesas", tz: "MART9:30" },
	{ location: "Pacific/Midway", tz: "SST11" },
	{ location: "Pacific/Nauru", tz: "NRT-12" },
	{ location: "Pacific/Niue", tz: "NUT11" },
	{ location: "Pacific/Norfolk", tz: "NFT-11:30" },
	{ location: "Pacific/Noumea", tz: "NCT-11" },
	{ location: "Pacific/Pago Pago", tz: "SST11" },
	{ location: "Pacific/Palau", tz: "PWT-9" },
	{ location: "Pacific/Pitcairn", tz: "PST8" },
	{ location: "Pacific/Ponape", tz: "PONT-11" },
	{ location: "Pacific/Port Moresby", tz: "PGT-10" },
	{ location: "Pacific/Rarotonga", tz: "CKT10" },
	{ location: "Pacific/Saipan", tz: "ChST-10" },
	{ location: "Pacific/Tahiti", tz: "TAHT10" },
	{ location: "Pacific/Tarawa", tz: "GILT-12" },
	{ location: "Pacific/Tongatapu", tz: "TOT-13" },
	{ location: "Pacific/Truk", tz: "TRUT-10" },
	{ location: "Pacific/Wake", tz: "WAKT-12" },
	{ location: "Pacific/Wallis", tz: "WFT-12" },
];
