// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Failure flag. ALWAYS a quoted JSON string ("true"/"false"), never a JSON
 * boolean. "true" means the request failed (still HTTP 200).
 */
export type ErrorFlag = 'true' | 'false';

/**
 * On/off flag as the firmware represents it: the literal strings "yes"/"no".
 * The firmware does NOT recognise true/1/on.
 */
export type YesNo = 'yes' | 'no';

/**
 * The canonical result envelope shared by most endpoints.
 */
export type SimpleResult = {
    error: ErrorFlag;
};

/**
 * Result envelope for the audio endpoints; description carries the spoken text, played filename, or an error reason.
 */
export type AudioResult = {
    error: ErrorFlag;
    /**
     * Spoken text / played filename on success, or a human-readable failure reason. Unescaped; may corrupt the JSON.
     */
    description?: string;
};

/**
 * Result envelope for ptzPreset; message is present only on failures.
 */
export type PresetResult = {
    error: ErrorFlag;
    /**
     * Failure reason - "Invalid query", "Wrong arguments", "-99", or raw text
     * from the backend script. A multi-word backend message is word-split
     * across repeated printf format cycles, corrupting the JSON (extra
     * unquoted-comma key/value pairs); `message` then holds only the first word.
     */
    message?: string;
};

/**
 * controlService response. A status query returns `status`; start/stop and
 * unmatched requests return `{}`; a blocklisted query string returns `error`.
 */
export type ServiceResult = {
    error?: ErrorFlag;
    /**
     * Backend service status text, injected raw (not JSON-escaped).
     */
    status?: string;
};

/**
 * testProxy response. `result` is the raw ipinfo.io JSON spliced in bare; absent on the error paths and possibly malformed if wget failed.
 */
export type ProxyResult = {
    error: ErrorFlag;
    /**
     * Raw JSON body returned by http://ipinfo.io, injected unescaped.
     */
    result?: {
        [key: string]: unknown;
    };
};

/**
 * firmwareUpgrade get=info response. Note local_fw is a BARE JSON boolean, unlike error which is a string.
 */
export type FwInfoResponse = {
    error?: ErrorFlag;
    /**
     * Installed firmware version.
     */
    fw_version?: string;
    /**
     * Latest version from the GitHub API; empty string if the live network call failed.
     */
    latest_fw?: string;
    /**
     * BARE JSON boolean (not a string) - true if a local firmware tgz is present.
     */
    local_fw?: boolean;
};

/**
 * wifi action=scan response. The array is always padded with a trailing empty-string element; SSIDs are unescaped.
 */
export type WifiScanResponse = {
    /**
     * ESSID strings, always terminated by an empty-string "" element.
     */
    wifi: Array<string>;
};

/**
 * wifi action=save body. Values bypass all validators (only JSON validity is checked).
 */
export type WifiSaveRequest = {
    /**
     * Network SSID (stored as wifi_ssid).
     */
    WIFI_ESSID?: string;
    /**
     * Network passphrase (stored as wifi_psk).
     */
    WIFI_PASSWORD?: string;
    /**
     * Passphrase confirmation - must equal WIFI_PASSWORD or the request fails. Never stored.
     */
    WIFI_PASSWORD2?: string;
};

/**
 * Device telemetry from status.json. All values are strings except none - ptz/go2rtc use the yes/no strings.
 */
export type StatusInfo = {
    name?: string;
    hostname?: string;
    fw_version?: string;
    home_version?: string;
    model_suffix?: string;
    ptz?: YesNo;
    go2rtc?: YesNo;
    /**
     * May be an empty string.
     */
    serial_number?: string;
    local_time?: string;
    uptime?: string;
    load_avg?: string;
    total_memory?: string;
    free_memory?: string;
    /**
     * Free percent (e.g. "42%") or "N/A".
     */
    free_sd?: string;
    local_ip?: string;
    netmask?: string;
    gateway?: string;
    mac_addr?: string;
    wlan_essid?: string;
    wlan_strength?: string;
};

/**
 * getLinks response. Stream fields are conditional on RTSP config; the two snapshot fields are always present.
 */
export type LinksResponse = {
    /**
     * RTSP URL for the low-resolution stream (conditional).
     */
    low_res_stream?: string;
    /**
     * RTSP URL for the high-resolution stream (conditional).
     */
    high_res_stream?: string;
    /**
     * RTSP URL for the audio stream (present when RTSP is enabled AND RTSP_AUDIO is not exactly no/none).
     */
    audio_stream?: string;
    /**
     * HTTP URL for a low-res snapshot (always present).
     */
    low_res_snapshot?: string;
    /**
     * HTTP URL for a high-res snapshot (always present).
     */
    high_res_snapshot?: string;
};

/**
 * getEventDirs response. May be malformed (trailing comma) if a non-14-char entry exists.
 */
export type EventDirsResponse = {
    records: Array<{
        /**
         * Human-readable label, e.g. "Date: 2024-08-24 Time: 15:00".
         */
        datetime?: string;
        /**
         * Raw 14-char directory name, e.g. "2024Y08M24D15H".
         */
        dirname?: string;
    }>;
};

/**
 * getEventFiles response on success. A missing/rejected dirname returns just {"error":"true"} instead.
 */
export type EventFilesResponse = {
    error: ErrorFlag;
    /**
     * YYYY-MM-DD derived from the directory name.
     */
    date?: string;
    records?: Array<{
        /**
         * e.g. "Time: 15:04".
         */
        time?: string;
        /**
         * Raw mp4 file name.
         */
        filename?: string;
        /**
         * Sibling .jpg thumbnail name, or empty string if none.
         */
        thumbfilename?: string;
    }>;
};

/**
 * timelapse action=list response. May be malformed (trailing comma) if a non-23-char .avi exists.
 */
export type TimelapseListResponse = {
    error: ErrorFlag;
    records?: Array<{
        /**
         * e.g. "Date: 2024-08-24".
         */
        date?: string;
        /**
         * e.g. "Time: 15:04:00".
         */
        time?: string;
        filename?: string;
    }>;
};

/**
 * Generic getConfigs response: an open map of string values read from the
 * chosen .conf file. ALWAYS includes a fake `"NULL":"NULL"` sentinel pair
 * that clients MUST strip. OpenAPI 3.0 cannot select a per-conf schema by
 * query value; see the named *Conf schemas for documented shapes.
 */
export type GetConfigsResponse = {
    [key: string]: string;
};

/**
 * Documentation-derived shape of the response for `getConfigs?conf=camera`.
 * Not referenced by the operation (3.0 cannot switch schema on a query value).
 * HOMEVER is appended by the script (raw/unescaped); the response also carries
 * the "NULL":"NULL" sentinel which is omitted here.
 */
export type CameraConf = {
    SWITCH_ON?: YesNo;
    SAVE_VIDEO_ON_MOTION?: YesNo;
    MOTION_DETECTION?: YesNo;
    /**
     * low | medium | high.
     */
    SENSITIVITY?: string;
    AI_HUMAN_DETECTION?: YesNo;
    AI_VEHICLE_DETECTION?: YesNo;
    AI_ANIMAL_DETECTION?: YesNo;
    FACE_DETECTION?: YesNo;
    MOTION_TRACKING?: YesNo;
    SOUND_DETECTION?: YesNo;
    /**
     * Numeric string, e.g. "80".
     */
    SOUND_SENSITIVITY?: string;
    LED?: YesNo;
    ROTATE?: YesNo;
    IR?: YesNo;
    /**
     * no | presets | 360.
     */
    CRUISE?: string;
    /**
     * Appended only for conf=camera; injected raw/unescaped.
     */
    HOMEVER?: string;
};

/**
 * Documentation-derived shape of the response for `getConfigs?conf=system`.
 * Not referenced by the operation. HOSTNAME is appended by the script; the
 * response also carries the "NULL":"NULL" sentinel which is omitted here.
 */
export type SystemConf = {
    HTTPD?: YesNo;
    TELNETD?: YesNo;
    SSHD?: YesNo;
    FTPD?: YesNo;
    BUSYBOX_FTPD?: YesNo;
    MDNSD?: YesNo;
    DISABLE_CLOUD?: YesNo;
    REC_WITHOUT_CLOUD?: YesNo;
    MQTT?: YesNo;
    RTSP?: YesNo;
    RTSP_ALT?: string;
    /**
     * high | low | both.
     */
    RTSP_STREAM?: string;
    /**
     * yes | no | none.
     */
    RTSP_AUDIO?: string;
    RTSP_STI?: YesNo;
    SPEAKER_AUDIO?: YesNo;
    SNAPSHOT?: YesNo;
    SNAPSHOT_VIDEO?: YesNo;
    SNAPSHOT_LOW?: YesNo;
    TIMELAPSE?: YesNo;
    TIMELAPSE_FTP?: YesNo;
    TIMELAPSE_FTP_SAME_NAME?: YesNo;
    TIMELAPSE_DT?: string;
    TIMELAPSE_VDT?: string;
    ONVIF?: YesNo;
    ONVIF_WSDD?: YesNo;
    ONVIF_PROFILE?: string;
    ONVIF_NETIF?: string;
    ONVIF_WM_SNAPSHOT?: YesNo;
    ONVIF_AUDIO_BC?: string;
    ONVIF_ENABLE_MEDIA2?: YesNo;
    ONVIF_FAULT_IF_UNKNOWN?: YesNo;
    ONVIF_FAULT_IF_SET?: YesNo;
    ONVIF_SYNOLOGY_NVR?: YesNo;
    TIME_OSD?: YesNo;
    NTPD?: YesNo;
    NTP_SERVER?: string;
    PROXYCHAINSNG?: YesNo;
    SWAP_FILE?: YesNo;
    SWAP_SWAPPINESS?: string;
    KERNEL_TUNING?: YesNo;
    RTSP_PORT?: string;
    HTTPD_PORT?: string;
    USERNAME?: string;
    PASSWORD?: string;
    TIMEZONE?: string;
    /**
     * autodetect | local | gmt.
     */
    EVENTS_TIME?: string;
    FREE_SPACE?: string;
    FTP_UPLOAD?: YesNo;
    FTP_HOST?: string;
    FTP_DIR?: string;
    FTP_DIR_TREE?: YesNo;
    FTP_USERNAME?: string;
    FTP_PASSWORD?: string;
    FTP_FILE_DELETE_AFTER_UPLOAD?: YesNo;
    SSH_PASSWORD?: string;
    CRONTAB?: string;
    DEBUG_LOG?: YesNo;
    STATIC_IP?: string;
    STATIC_MASK?: string;
    STATIC_GW?: string;
    STATIC_DNS1?: string;
    STATIC_DNS2?: string;
    CUSTOM_WATERMARK?: YesNo;
    /**
     * Appended only for conf=system.
     */
    HOSTNAME?: string;
};

/**
 * Documentation-derived shape of `getConfigs?conf=mqtt` (reads mqttv4.conf). Not referenced by the operation. Omits the NULL sentinel.
 */
export type MqttConf = {
    MQTT_IP?: string;
    MQTT_PORT?: string;
    MQTT_TLS?: string;
    MQTT_CLIENT_ID?: string;
    MQTT_USER?: string;
    MQTT_PASSWORD?: string;
    MQTT_PREFIX?: string;
    TOPIC_BIRTH_WILL?: string;
    TOPIC_MOTION?: string;
    TOPIC_MOTION_IMAGE?: string;
    /**
     * Decimal seconds; setConfigs only accepts values <= 5.0.
     */
    MOTION_IMAGE_DELAY?: string;
    TOPIC_MOTION_FILES?: string;
    TOPIC_SOUND_DETECTION?: string;
    BIRTH_MSG?: string;
    WILL_MSG?: string;
    MOTION_START_MSG?: string;
    MOTION_STOP_MSG?: string;
    AI_HUMAN_DETECTION_MSG?: string;
    AI_VEHICLE_DETECTION_MSG?: string;
    AI_ANIMAL_DETECTION_MSG?: string;
    BABY_CRYING_MSG?: string;
    SOUND_DETECTION_MSG?: string;
    MQTT_KEEPALIVE?: string;
    MQTT_QOS?: string;
    MQTT_RETAIN_BIRTH_WILL?: string;
    MQTT_RETAIN_MOTION?: string;
    MQTT_RETAIN_MOTION_IMAGE?: string;
    MQTT_RETAIN_MOTION_FILES?: string;
    MQTT_RETAIN_SOUND_DETECTION?: string;
};

/**
 * Documentation-derived shape of `getConfigs?conf=mqtt_advertise`. Not referenced by the operation. Omits the NULL sentinel.
 */
export type MqttAdvertiseConf = {
    MQTT_ADV_LINK_ENABLE?: YesNo;
    MQTT_ADV_LINK_BOOT?: YesNo;
    MQTT_ADV_LINK_CRON?: YesNo;
    MQTT_ADV_LINK_CRONTAB?: string;
    MQTT_ADV_LINK_TOPIC?: string;
    MQTT_ADV_LINK_RETAIN?: string;
    MQTT_ADV_LINK_QOS?: string;
    MQTT_ADV_INFO_GLOBAL_ENABLE?: YesNo;
    MQTT_ADV_INFO_GLOBAL_BOOT?: YesNo;
    MQTT_ADV_INFO_GLOBAL_CRON?: YesNo;
    MQTT_ADV_INFO_GLOBAL_CRONTAB?: string;
    MQTT_ADV_INFO_GLOBAL_TOPIC?: string;
    MQTT_ADV_INFO_GLOBAL_RETAIN?: string;
    MQTT_ADV_INFO_GLOBAL_QOS?: string;
    MQTT_ADV_CAMERA_SETTING_ENABLE?: YesNo;
    MQTT_ADV_CAMERA_SETTING_BOOT?: YesNo;
    MQTT_ADV_CAMERA_SETTING_CRON?: YesNo;
    MQTT_ADV_CAMERA_SETTING_CRONTAB?: string;
    MQTT_ADV_CAMERA_SETTING_TOPIC?: string;
    MQTT_ADV_CAMERA_SETTING_RETAIN?: string;
    MQTT_ADV_CAMERA_SETTING_QOS?: string;
    MQTT_ADV_TELEMETRY_ENABLE?: YesNo;
    MQTT_ADV_TELEMETRY_BOOT?: YesNo;
    MQTT_ADV_TELEMETRY_CRON?: YesNo;
    MQTT_ADV_TELEMETRY_CRONTAB?: string;
    MQTT_ADV_TELEMETRY_TOPIC?: string;
    MQTT_ADV_TELEMETRY_RETAIN?: string;
    MQTT_ADV_TELEMETRY_QOS?: string;
    HOMEASSISTANT_ENABLE?: YesNo;
    HOMEASSISTANT_BOOT?: YesNo;
    HOMEASSISTANT_CRON?: YesNo;
    HOMEASSISTANT_CRONTAB?: string;
    HOMEASSISTANT_MQTT_PREFIX?: string;
    HOMEASSISTANT_NAME?: string;
    HOMEASSISTANT_IDENTIFIERS?: string;
    HOMEASSISTANT_MANUFACTURER?: string;
    HOMEASSISTANT_MODEL?: string;
    HOMEASSISTANT_RETAIN?: string;
    HOMEASSISTANT_QOS?: string;
};

/**
 * Documentation-derived shape of `getConfigs?conf=ptz_presets`. Keys are
 * numeric index strings ("0", "1", ...) mapping to preset names (empty when
 * unset). Not referenced by the operation. Omits the NULL sentinel.
 */
export type PtzPresetsConf = {
    [key: string]: string;
};

/**
 * Documentation-derived shape of `getConfigs?conf=proxychains`. The script
 * returns a single PROXYCHAINS_SERVERS field (semicolon-joined server lines
 * from the [ProxyList] section), injected raw. Omits the NULL sentinel.
 */
export type ProxychainsConf = {
    /**
     * Semicolon-joined proxy server lines; raw/unescaped.
     */
    PROXYCHAINS_SERVERS?: string;
};

export type SetCameraSettingsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Only `no` powers the camera off (also runs ipc_cmd -T); any other value powers it on.
         */
        switch_on?: string;
        /**
         * Only `no` maps to `always`; any other value maps to `detect`.
         */
        save_video_on_motion?: string;
        /**
         * Enum yes/no. Any other value is silently dropped (keeps camera.conf default). Consumed only on 11/12 firmware.
         */
        motion_detection?: YesNo;
        /**
         * Enum. Any other value is silently dropped (no command run) but still returns error=false.
         */
        sensitivity?: 'low' | 'medium' | 'high';
        /**
         * Only `no` means off; any other value means on. On 11/12 firmware it is
         * applied only when motion_detection=no; when motion_detection != no it is
         * silently ignored. On non-11/12 firmware it is always applied (via
         * ipc_cmd -a), unlike vehicle/animal which are never applied there.
         */
        ai_human_detection?: string;
        /**
         * Only `no` means off; any other value means on. Ignored unless 11/12 firmware AND motion_detection=no.
         */
        ai_vehicle_detection?: string;
        /**
         * Only `no` means off; any other value means on. Ignored unless 11/12 firmware AND motion_detection=no.
         */
        ai_animal_detection?: string;
        /**
         * Only `no` means off; any other value means on.
         */
        face_detection?: string;
        /**
         * Only `no` means off; any other value means on.
         */
        motion_tracking?: string;
        /**
         * Only `no` means off; any other value means on.
         */
        sound_detection?: string;
        /**
         * Exact-string enum. Note the gap - 55/65/75/85 are NOT accepted. Any other value is silently dropped.
         */
        sound_sensitivity?: '30' | '35' | '40' | '45' | '50' | '60' | '70' | '80' | '90';
        /**
         * Only `no` means off; any other value means on.
         */
        led?: string;
        /**
         * Only `no` means off; any other value means on.
         */
        ir?: string;
        /**
         * Only `no` means off; any other value means on.
         */
        rotate?: string;
        /**
         * Enum. Any other value is silently dropped. `presets` and `360` add a 0.5s sleep.
         */
        cruise?: 'no' | 'presets' | '360';
    };
    url: '/cgi-bin/camera_settings.sh';
};

export type SetCameraSettingsErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type SetCameraSettingsResponses = {
    /**
     * Always returned (success or validation failure). Check the error field.
     */
    200: SimpleResult;
};

export type SetCameraSettingsResponse = SetCameraSettingsResponses[keyof SetCameraSettingsResponses];

export type GetConfigsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Config file to read. Known/meaningful values only; the script accepts
         * any value (blocklist, not allowlist). `mqtt` reads mqttv4.conf.
         */
        conf?: 'camera' | 'system' | 'mqtt' | 'mqtt_advertise' | 'proxychains' | 'ptz_presets';
    };
    url: '/cgi-bin/get_configs.sh';
};

export type GetConfigsErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type GetConfigsResponses = {
    /**
     * Always returned. A validation failure is `{"error":"true"}`; a missing
     * file is `{"NULL":"NULL"}`; otherwise the conf contents plus the trailing
     * NULL sentinel.
     */
    200: GetConfigsResponse;
};

export type GetConfigsResponse2 = GetConfigsResponses[keyof GetConfigsResponses];

export type SetConfigsData = {
    /**
     * Flat KEY->value map. See operation description for special keys.
     */
    body: {
        [key: string]: string;
    };
    path?: never;
    query?: {
        /**
         * Target config file. `mqtt` writes mqttv4.conf. Same blocklist-only handling as getConfigs.
         */
        conf?: 'camera' | 'system' | 'mqtt' | 'mqtt_advertise' | 'proxychains' | 'ptz_presets';
    };
    url: '/cgi-bin/set_configs.sh';
};

export type SetConfigsErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type SetConfigsResponses = {
    /**
     * Always returned. `{"error":"true"}` on invalid query/body/key, else `{"error":"false"}` (even if individual writes no-op).
     */
    200: SimpleResult;
};

export type SetConfigsResponse = SetConfigsResponses[keyof SetConfigsResponses];

export type GetStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cgi-bin/status.json';
};

export type GetStatusErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type GetStatusResponses = {
    /**
     * Device telemetry (always).
     */
    200: StatusInfo;
};

export type GetStatusResponse = GetStatusResponses[keyof GetStatusResponses];

export type GetHostnameData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cgi-bin/hostname.js';
};

export type GetHostnameErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type GetHostnameResponses = {
    /**
     * A JavaScript assignment statement (always).
     */
    200: Blob | File;
};

export type GetHostnameResponse = GetHostnameResponses[keyof GetHostnameResponses];

export type GetLinksData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cgi-bin/links.sh';
};

export type GetLinksErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type GetLinksResponses = {
    /**
     * Stream/snapshot links (always). Stream fields are conditional.
     */
    200: LinksResponse;
};

export type GetLinksResponse = GetLinksResponses[keyof GetLinksResponses];

export type TestProxyData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Must be the first parameter and keyed `proxy`. Value `1` = via proxychains4; any other value = direct.
         */
        proxy: string;
    };
    url: '/cgi-bin/proxy.sh';
};

export type TestProxyErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type TestProxyResponses = {
    /**
     * Always returned. `result` present on success (raw ipinfo.io JSON), absent on the error paths.
     */
    200: ProxyResult;
};

export type TestProxyResponse = TestProxyResponses[keyof TestProxyResponses];

export type GetEventDirsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cgi-bin/eventsdir.sh';
};

export type GetEventDirsErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type GetEventDirsResponses = {
    /**
     * List of event directories (always).
     */
    200: EventDirsResponse;
};

export type GetEventDirsResponse = GetEventDirsResponses[keyof GetEventDirsResponses];

export type GetEventFilesData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Event directory name (e.g. 2024Y08M24D15H). Format not enforced; empty value lists the record root.
         */
        dirname: string;
    };
    url: '/cgi-bin/eventsfile.sh';
};

export type GetEventFilesErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type GetEventFilesResponses = {
    /**
     * Recordings in the directory, or `{"error":"true"}` if dirname is missing/rejected.
     */
    200: EventFilesResponse;
};

export type GetEventFilesResponse = GetEventFilesResponses[keyof GetEventFilesResponses];

export type DeleteEventDirData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Directory to delete. `all` deletes every recording. Format not enforced; unquoted into rm -rf.
         */
        dir?: string;
    };
    url: '/cgi-bin/eventsdirdel.sh';
};

export type DeleteEventDirErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type DeleteEventDirResponses = {
    /**
     * Always `{"error":"false"}` on the pass path (even on no-op), `{"error":"true"}` on a blocklisted query string.
     */
    200: SimpleResult;
};

export type DeleteEventDirResponse = DeleteEventDirResponses[keyof DeleteEventDirResponses];

export type DeleteEventFileData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The `<dirname>/<filename>` path, 27 or 29 chars with fixed Y/M/D/H/M/S marker positions.
         */
        file: string;
    };
    url: '/cgi-bin/eventsfiledel.sh';
};

export type DeleteEventFileErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type DeleteEventFileResponses = {
    /**
     * `{"error":"false"}` on success (even if files absent), `{"error":"true"}` on missing/invalid file.
     */
    200: SimpleResult;
};

export type DeleteEventFileResponse = DeleteEventFileResponses[keyof DeleteEventFileResponses];

export type GetSnapshotData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Resolution. Out-of-domain values silently fall back to `high`.
         */
        res?: 'low' | 'high';
        /**
         * Overlay the watermark. Out-of-domain values silently fall back to `no`.
         */
        watermark?: YesNo;
        /**
         * If `yes`, return base64 text under `image/jpeg;base64` instead of binary. Out-of-domain values fall back to `no`.
         */
        base64?: YesNo;
        /**
         * Optional bare filename to save the snapshot into /tmp/sd/record. Must
         * pass validateBaseName (no leading `.`, no `/` or blocklisted chars). If
         * valid, the response is JSON instead of an image; if invalid it is
         * silently ignored (inline image returned).
         */
        file?: string;
    };
    url: '/cgi-bin/snapshot.sh';
};

export type GetSnapshotErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type GetSnapshotResponses = {
    /**
     * JPEG (binary or base64) on the image paths, or JSON on the save-to-disk
     * and validation-failure paths. Content type indicates which.
     */
    200: SimpleResult;
};

export type GetSnapshotResponse = GetSnapshotResponses[keyof GetSnapshotResponses];

export type StartRecordingData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Recording length in seconds (must be first param). Defaults to 60. validateNumber charset only.
         */
        time?: string;
    };
    url: '/cgi-bin/record.sh';
};

export type StartRecordingErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type StartRecordingResponses = {
    /**
     * `{"error":"false"}` on success/default, `{"error":"true"}` on invalid query string or non-numeric time.
     */
    200: SimpleResult;
};

export type StartRecordingResponse = StartRecordingResponses[keyof StartRecordingResponses];

export type GetLastRecordedVideoData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 0/1 = latest; >0 = Nth oldest in the current hour folder (clamped);
         * <0 = wait for the next video (up to ~80s). Not numerically validated.
         */
        oldness?: string;
        /**
         * 1=relative path (default), 2=absolute URL, 3=inline mp4, 4=attachment
         * mp4. Any other value falls into the type=1 branch.
         */
        type?: '1' | '2' | '3' | '4';
    };
    url: '/cgi-bin/getlastrecordedvideo.sh';
};

export type GetLastRecordedVideoErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type GetLastRecordedVideoResponses = {
    /**
     * Plain-text path/URL (type 1/2), raw mp4 (type 3/4), or JSON error on a
     * blocklisted query string. Content type indicates which.
     */
    200: SimpleResult;
};

export type GetLastRecordedVideoResponse = GetLastRecordedVideoResponses[keyof GetLastRecordedVideoResponses];

export type TimelapseData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Only `list` and `delete` produce output; any other value returns an empty body with no headers.
         */
        action: 'list' | 'delete';
        /**
         * Required for action=delete. 23-char `.avi` name with fixed separator positions (validateTLFile).
         */
        file?: string;
    };
    url: '/cgi-bin/timelapse.sh';
};

export type TimelapseErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type TimelapseResponses = {
    /**
     * For action=list, a records object; for action=delete, `{"error":...}`.
     * For any other action the body is EMPTY with no Content-type header.
     */
    200: TimelapseListResponse | SimpleResult;
};

export type TimelapseResponse = TimelapseResponses[keyof TimelapseResponses];

export type PtzMoveData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Movement mode. Unknown values return error=true.
         */
        action?: 'step' | 'abs' | 'rel' | 'cont';
        /**
         * X target/delta for abs/rel. validateNumber (allows comma, so `1,2` is possible). Default 9999.
         */
        x?: string;
        /**
         * Y target/delta for abs/rel. validateNumber. Default 9999.
         */
        y?: string;
        /**
         * Direction for step/cont. Stock values up|down|left|right|up_left|
         * up_right|down_left|down_right|stop. Only charset-validated; a `_`
         * triggers two sequential moves. Defaults to `none`: for action=step/cont
         * with dir omitted or `none`, nothing moves but the response is still
         * `{"error":"false"}`.
         */
        dir?: string;
        /**
         * Seconds to hold before stop (step only). validateNumber, UNBOUNDED. Default 0.3.
         */
        time?: string;
    };
    url: '/cgi-bin/ptz.sh';
};

export type PtzMoveErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type PtzMoveResponses = {
    /**
     * `{"error":"false"}` whenever the query validates - this does NOT imply an
     * action was executed (action=step/cont with dir omitted or `none` moves
     * nothing yet still returns error=false). `{"error":"true"}` on an unknown
     * action or any validator failure.
     */
    200: SimpleResult;
};

export type PtzMoveResponse = PtzMoveResponses[keyof PtzMoveResponses];

export type PtzPresetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * go_preset | add_preset | del_preset | set_home_position. `none`/`get_presets` are refused (message -99). set_home_position is supported by the backend but unused by the stock UI. Forwarded unquoted.
         */
        action: 'go_preset' | 'add_preset' | 'del_preset' | 'set_home_position';
        /**
         * Preset number, or the literal `all`. validateNumber otherwise. Omitted -> not passed.
         */
        num?: string;
        /**
         * Preset name (validateString - rejects `. , & ( )` etc). Omitted -> not passed.
         */
        name?: string;
    };
    url: '/cgi-bin/preset.sh';
};

export type PtzPresetErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type PtzPresetResponses = {
    /**
     * `{"error":"false"}` when the external script succeeds (empty stdout),
     * else `{"error":"true","message":"<msg>"}` (Invalid query, Wrong
     * arguments, -99, or raw backend text). NOTE: multi-word backend messages
     * (e.g. "Preset number out of range") are word-split across repeated printf
     * format cycles, producing malformed JSON with extra unquoted-comma
     * key/value pairs; `message` then holds only the first word.
     */
    200: PresetResult;
};

export type PtzPresetResponse = PtzPresetResponses[keyof PtzPresetResponses];

export type WifiData = {
    /**
     * Required only for action=save. Single-line JSON object of Wi-Fi credentials.
     */
    body?: WifiSaveRequest;
    path?: never;
    query: {
        /**
         * `scan` (invoked as GET in the firmware) or `save` (POST with body).
         * Any other value returns an empty body with no headers.
         */
        action: 'scan' | 'save';
    };
    url: '/cgi-bin/wifi.sh';
};

export type WifiErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type WifiResponses = {
    /**
     * For action=scan, `{"wifi":[...]}`; for action=save, `{"error":...}`. Any
     * other action returns an empty body with no Content-type header.
     */
    200: WifiScanResponse | SimpleResult;
};

export type WifiResponse = WifiResponses[keyof WifiResponses];

export type SpeakTextData = {
    /**
     * UTF-8 text to speak (first line only is used).
     */
    body: string;
    path?: never;
    query?: {
        /**
         * BCP-47-ish 5-char code like `en-US` (validateLang - exactly 5 chars, `[A-Za-z-]`). Default en-US.
         */
        lang?: string;
        /**
         * Linear gain (pcmvol -g). Setting it forces linear mode. validateNumber. Default 1. Unused by stock UI.
         */
        vol?: string;
        /**
         * dB gain (pcmvol -G). Setting it forces dB mode. validateNumber. Default 0.
         */
        voldb?: string;
    };
    url: '/cgi-bin/speak.sh';
};

export type SpeakTextErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type SpeakTextResponses = {
    /**
     * `{"error":"false","description":"<text>"}` on success, else
     * `{"error":"true","description":"<reason>"}`. Some failure paths omit the
     * Content-type header.
     */
    200: AudioResult;
};

export type SpeakTextResponse = SpeakTextResponses[keyof SpeakTextResponses];

export type PlayAudioData = {
    /**
     * Audio payload - multipart/form-data file field or a raw PCM/WAV stream.
     */
    body: {
        /**
         * The audio file (stock UI uses a FormData field named `file`).
         */
        file?: Blob | File;
    };
    path?: never;
    query?: {
        /**
         * Linear gain (pcmvol -g). Honoured only as the FIRST param. validateNumber. Default 1.
         */
        vol?: string;
        /**
         * dB gain (pcmvol -G). Honoured only as the FIRST param. validateNumber. Default 0.
         */
        voldb?: string;
    };
    url: '/cgi-bin/speaker.sh';
};

export type PlayAudioErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type PlayAudioResponses = {
    /**
     * `{"error":"false","description":""}` on success (mounted path returns
     * before playback finishes), else `{"error":"true","description":"<reason>"}`.
     */
    200: AudioResult;
};

export type PlayAudioResponse = PlayAudioResponses[keyof PlayAudioResponses];

export type PlayAudioFileData = {
    /**
     * Filename relative to /tmp/sd/audio (first line only; unvalidated, path traversal possible).
     */
    body: string;
    path?: never;
    query?: {
        /**
         * dB gain (pcmvol -G). validateNumber. Default 1.
         */
        voldb?: string;
    };
    url: '/cgi-bin/speaker_file.sh';
};

export type PlayAudioFileErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type PlayAudioFileResponses = {
    /**
     * `{"error":"false","description":"<filename>"}` on success, else an error
     * object. The not-found and audio-disabled paths emit MALFORMED JSON.
     */
    200: AudioResult;
};

export type PlayAudioFileResponse = PlayAudioFileResponses[keyof PlayAudioFileResponses];

export type FirmwareUpgradeData = {
    body?: never;
    path?: never;
    query: {
        /**
         * `info` (JSON version info) or `upgrade` (destructive; text/html, then
         * reboots). Must be the only query param. Other values -> empty 200.
         */
        get: 'info' | 'upgrade';
    };
    url: '/cgi-bin/fw_upgrade.sh';
};

export type FirmwareUpgradeErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type FirmwareUpgradeResponses = {
    /**
     * JSON version info for get=info; text/html status for get=upgrade; JSON
     * error on a blocklisted query string; empty body for an unrecognised get.
     */
    200: FwInfoResponse;
};

export type FirmwareUpgradeResponse = FirmwareUpgradeResponses[keyof FirmwareUpgradeResponses];

export type RebootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cgi-bin/reboot.sh';
};

export type RebootErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type RebootResponses = {
    /**
     * Always `{"error":"false"}`, sent just before the reboot.
     */
    200: SimpleResult;
};

export type RebootResponse = RebootResponses[keyof RebootResponses];

export type ResetConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cgi-bin/reset.sh';
};

export type ResetConfigErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type ResetConfigResponses = {
    /**
     * Always `{"error":"false"}`, even if the underlying rm/tar failed.
     */
    200: SimpleResult;
};

export type ResetConfigResponse = ResetConfigResponses[keyof ResetConfigResponses];

export type SaveConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/cgi-bin/save.sh';
};

export type SaveConfigErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type SaveConfigResponses = {
    /**
     * Binary bzip2 tar archive (always).
     */
    200: Blob | File;
};

export type SaveConfigResponse = SaveConfigResponses[keyof SaveConfigResponses];

export type LoadConfigData = {
    /**
     * Multipart upload of a config.tar.bz2 in the `files[]` field. Max 10000 bytes.
     */
    body: {
        /**
         * The config.tar.bz2 archive (must contain system.conf and camera.conf).
         */
        'files[]'?: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/cgi-bin/load.sh';
};

export type LoadConfigErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type LoadConfigResponses = {
    /**
     * text/html "Upload completed successfully, restart your camera" or
     * "Upload failed". An over-size upload returns an empty body.
     */
    200: string;
};

export type LoadConfigResponse = LoadConfigResponses[keyof LoadConfigResponses];

export type ControlServiceData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Service name. start/stop: rtsp|onvif|wsdd|ftpd|mqtt|mqtt-config|
         * mp4record|all. status: same set WITHOUT `all`. An unmatched name yields
         * an empty `{}`.
         */
        name?: 'rtsp' | 'onvif' | 'wsdd' | 'ftpd' | 'mqtt' | 'mqtt-config' | 'mp4record' | 'all';
        /**
         * start | stop | status. Any other value yields an empty `{}`.
         */
        action?: 'start' | 'stop' | 'status';
        /**
         * Positional backend arg for rtsp/onvif/ftpd start. Defaults to the literal string `none`. Not individually validated.
         */
        param1?: string;
        /**
         * Positional backend arg for rtsp/onvif start. Defaults to the literal string `none`. Not individually validated.
         */
        param2?: string;
    };
    url: '/cgi-bin/service.sh';
};

export type ControlServiceErrors = {
    /**
     * Returned by BusyBox httpd itself (NOT the CGI scripts) when HTTP Basic auth
     * is enabled and the request is missing/invalid credentials.
     */
    401: unknown;
};

export type ControlServiceResponses = {
    /**
     * `{"status":"..."}` for a matched status query, `{}` for start/stop and
     * unmatched requests, `{"error":"true"}` for a blocklisted query string.
     */
    200: ServiceResult;
};

export type ControlServiceResponse = ControlServiceResponses[keyof ControlServiceResponses];
