// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * Failure flag. ALWAYS a quoted JSON string ("true"/"false"), never a JSON
 * boolean. "true" means the request failed (still HTTP 200).
 */
export const zErrorFlag = z.enum(['true', 'false']);

/**
 * On/off flag as the firmware represents it: the literal strings "yes"/"no".
 * The firmware does NOT recognise true/1/on.
 */
export const zYesNo = z.enum(['yes', 'no']);

/**
 * The canonical result envelope shared by most endpoints.
 */
export const zSimpleResult = z.object({
    error: zErrorFlag
});

/**
 * Result envelope for the audio endpoints; description carries the spoken text, played filename, or an error reason.
 */
export const zAudioResult = z.object({
    error: zErrorFlag,
    description: z.string().optional()
});

/**
 * Result envelope for ptzPreset; message is present only on failures.
 */
export const zPresetResult = z.object({
    error: zErrorFlag,
    message: z.string().optional()
});

/**
 * controlService response. A status query returns `status`; start/stop and
 * unmatched requests return `{}`; a blocklisted query string returns `error`.
 */
export const zServiceResult = z.object({
    error: zErrorFlag.optional(),
    status: z.string().optional()
});

/**
 * testProxy response. `result` is the raw ipinfo.io JSON spliced in bare; absent on the error paths and possibly malformed if wget failed.
 */
export const zProxyResult = z.object({
    error: zErrorFlag,
    result: z.record(z.string(), z.unknown()).optional()
});

/**
 * firmwareUpgrade get=info response. Note local_fw is a BARE JSON boolean, unlike error which is a string.
 */
export const zFwInfoResponse = z.object({
    error: zErrorFlag.optional(),
    fw_version: z.string().optional(),
    latest_fw: z.string().optional(),
    local_fw: z.boolean().optional()
});

/**
 * wifi action=scan response. The array is always padded with a trailing empty-string element; SSIDs are unescaped.
 */
export const zWifiScanResponse = z.object({
    wifi: z.array(z.string())
});

/**
 * wifi action=save body. Values bypass all validators (only JSON validity is checked).
 */
export const zWifiSaveRequest = z.object({
    WIFI_ESSID: z.string().optional(),
    WIFI_PASSWORD: z.string().optional(),
    WIFI_PASSWORD2: z.string().optional()
});

/**
 * Device telemetry from status.json. All values are strings except none - ptz/go2rtc use the yes/no strings.
 */
export const zStatusInfo = z.object({
    name: z.string().optional(),
    hostname: z.string().optional(),
    fw_version: z.string().optional(),
    home_version: z.string().optional(),
    model_suffix: z.string().optional(),
    ptz: zYesNo.optional(),
    go2rtc: zYesNo.optional(),
    serial_number: z.string().optional(),
    local_time: z.string().optional(),
    uptime: z.string().optional(),
    load_avg: z.string().optional(),
    total_memory: z.string().optional(),
    free_memory: z.string().optional(),
    free_sd: z.string().optional(),
    local_ip: z.string().optional(),
    netmask: z.string().optional(),
    gateway: z.string().optional(),
    mac_addr: z.string().optional(),
    wlan_essid: z.string().optional(),
    wlan_strength: z.string().optional()
});

/**
 * getLinks response. Stream fields are conditional on RTSP config; the two snapshot fields are always present.
 */
export const zLinksResponse = z.object({
    low_res_stream: z.string().optional(),
    high_res_stream: z.string().optional(),
    audio_stream: z.string().optional(),
    low_res_snapshot: z.string().optional(),
    high_res_snapshot: z.string().optional()
});

/**
 * getEventDirs response. May be malformed (trailing comma) if a non-14-char entry exists.
 */
export const zEventDirsResponse = z.object({
    records: z.array(z.object({
        datetime: z.string().optional(),
        dirname: z.string().optional()
    }))
});

/**
 * getEventFiles response on success. A missing/rejected dirname returns just {"error":"true"} instead.
 */
export const zEventFilesResponse = z.object({
    error: zErrorFlag,
    date: z.string().optional(),
    records: z.array(z.object({
        time: z.string().optional(),
        filename: z.string().optional(),
        thumbfilename: z.string().optional()
    })).optional()
});

/**
 * timelapse action=list response. May be malformed (trailing comma) if a non-23-char .avi exists.
 */
export const zTimelapseListResponse = z.object({
    error: zErrorFlag,
    records: z.array(z.object({
        date: z.string().optional(),
        time: z.string().optional(),
        filename: z.string().optional()
    })).optional()
});

/**
 * Generic getConfigs response: an open map of string values read from the
 * chosen .conf file. ALWAYS includes a fake `"NULL":"NULL"` sentinel pair
 * that clients MUST strip. OpenAPI 3.0 cannot select a per-conf schema by
 * query value; see the named *Conf schemas for documented shapes.
 */
export const zGetConfigsResponse = z.record(z.string(), z.string());

/**
 * Documentation-derived shape of the response for `getConfigs?conf=camera`.
 * Not referenced by the operation (3.0 cannot switch schema on a query value).
 * HOMEVER is appended by the script (raw/unescaped); the response also carries
 * the "NULL":"NULL" sentinel which is omitted here.
 */
export const zCameraConf = z.object({
    SWITCH_ON: zYesNo.optional(),
    SAVE_VIDEO_ON_MOTION: zYesNo.optional(),
    MOTION_DETECTION: zYesNo.optional(),
    SENSITIVITY: z.string().optional(),
    AI_HUMAN_DETECTION: zYesNo.optional(),
    AI_VEHICLE_DETECTION: zYesNo.optional(),
    AI_ANIMAL_DETECTION: zYesNo.optional(),
    FACE_DETECTION: zYesNo.optional(),
    MOTION_TRACKING: zYesNo.optional(),
    SOUND_DETECTION: zYesNo.optional(),
    SOUND_SENSITIVITY: z.string().optional(),
    LED: zYesNo.optional(),
    ROTATE: zYesNo.optional(),
    IR: zYesNo.optional(),
    CRUISE: z.string().optional(),
    HOMEVER: z.string().optional()
});

/**
 * Documentation-derived shape of the response for `getConfigs?conf=system`.
 * Not referenced by the operation. HOSTNAME is appended by the script; the
 * response also carries the "NULL":"NULL" sentinel which is omitted here.
 */
export const zSystemConf = z.object({
    HTTPD: zYesNo.optional(),
    TELNETD: zYesNo.optional(),
    SSHD: zYesNo.optional(),
    FTPD: zYesNo.optional(),
    BUSYBOX_FTPD: zYesNo.optional(),
    MDNSD: zYesNo.optional(),
    DISABLE_CLOUD: zYesNo.optional(),
    REC_WITHOUT_CLOUD: zYesNo.optional(),
    MQTT: zYesNo.optional(),
    RTSP: zYesNo.optional(),
    RTSP_ALT: z.string().optional(),
    RTSP_STREAM: z.string().optional(),
    RTSP_AUDIO: z.string().optional(),
    RTSP_STI: zYesNo.optional(),
    SPEAKER_AUDIO: zYesNo.optional(),
    SNAPSHOT: zYesNo.optional(),
    SNAPSHOT_VIDEO: zYesNo.optional(),
    SNAPSHOT_LOW: zYesNo.optional(),
    TIMELAPSE: zYesNo.optional(),
    TIMELAPSE_FTP: zYesNo.optional(),
    TIMELAPSE_FTP_SAME_NAME: zYesNo.optional(),
    TIMELAPSE_DT: z.string().optional(),
    TIMELAPSE_VDT: z.string().optional(),
    ONVIF: zYesNo.optional(),
    ONVIF_WSDD: zYesNo.optional(),
    ONVIF_PROFILE: z.string().optional(),
    ONVIF_NETIF: z.string().optional(),
    ONVIF_WM_SNAPSHOT: zYesNo.optional(),
    ONVIF_AUDIO_BC: z.string().optional(),
    ONVIF_ENABLE_MEDIA2: zYesNo.optional(),
    ONVIF_FAULT_IF_UNKNOWN: zYesNo.optional(),
    ONVIF_FAULT_IF_SET: zYesNo.optional(),
    ONVIF_SYNOLOGY_NVR: zYesNo.optional(),
    TIME_OSD: zYesNo.optional(),
    NTPD: zYesNo.optional(),
    NTP_SERVER: z.string().optional(),
    PROXYCHAINSNG: zYesNo.optional(),
    SWAP_FILE: zYesNo.optional(),
    SWAP_SWAPPINESS: z.string().optional(),
    KERNEL_TUNING: zYesNo.optional(),
    RTSP_PORT: z.string().optional(),
    HTTPD_PORT: z.string().optional(),
    USERNAME: z.string().optional(),
    PASSWORD: z.string().optional(),
    TIMEZONE: z.string().optional(),
    EVENTS_TIME: z.string().optional(),
    FREE_SPACE: z.string().optional(),
    FTP_UPLOAD: zYesNo.optional(),
    FTP_HOST: z.string().optional(),
    FTP_DIR: z.string().optional(),
    FTP_DIR_TREE: zYesNo.optional(),
    FTP_USERNAME: z.string().optional(),
    FTP_PASSWORD: z.string().optional(),
    FTP_FILE_DELETE_AFTER_UPLOAD: zYesNo.optional(),
    SSH_PASSWORD: z.string().optional(),
    CRONTAB: z.string().optional(),
    DEBUG_LOG: zYesNo.optional(),
    STATIC_IP: z.string().optional(),
    STATIC_MASK: z.string().optional(),
    STATIC_GW: z.string().optional(),
    STATIC_DNS1: z.string().optional(),
    STATIC_DNS2: z.string().optional(),
    CUSTOM_WATERMARK: zYesNo.optional(),
    HOSTNAME: z.string().optional()
});

/**
 * Documentation-derived shape of `getConfigs?conf=mqtt` (reads mqttv4.conf). Not referenced by the operation. Omits the NULL sentinel.
 */
export const zMqttConf = z.object({
    MQTT_IP: z.string().optional(),
    MQTT_PORT: z.string().optional(),
    MQTT_TLS: z.string().optional(),
    MQTT_CLIENT_ID: z.string().optional(),
    MQTT_USER: z.string().optional(),
    MQTT_PASSWORD: z.string().optional(),
    MQTT_PREFIX: z.string().optional(),
    TOPIC_BIRTH_WILL: z.string().optional(),
    TOPIC_MOTION: z.string().optional(),
    TOPIC_MOTION_IMAGE: z.string().optional(),
    MOTION_IMAGE_DELAY: z.string().optional(),
    TOPIC_MOTION_FILES: z.string().optional(),
    TOPIC_SOUND_DETECTION: z.string().optional(),
    BIRTH_MSG: z.string().optional(),
    WILL_MSG: z.string().optional(),
    MOTION_START_MSG: z.string().optional(),
    MOTION_STOP_MSG: z.string().optional(),
    AI_HUMAN_DETECTION_MSG: z.string().optional(),
    AI_VEHICLE_DETECTION_MSG: z.string().optional(),
    AI_ANIMAL_DETECTION_MSG: z.string().optional(),
    BABY_CRYING_MSG: z.string().optional(),
    SOUND_DETECTION_MSG: z.string().optional(),
    MQTT_KEEPALIVE: z.string().optional(),
    MQTT_QOS: z.string().optional(),
    MQTT_RETAIN_BIRTH_WILL: z.string().optional(),
    MQTT_RETAIN_MOTION: z.string().optional(),
    MQTT_RETAIN_MOTION_IMAGE: z.string().optional(),
    MQTT_RETAIN_MOTION_FILES: z.string().optional(),
    MQTT_RETAIN_SOUND_DETECTION: z.string().optional()
});

/**
 * Documentation-derived shape of `getConfigs?conf=mqtt_advertise`. Not referenced by the operation. Omits the NULL sentinel.
 */
export const zMqttAdvertiseConf = z.object({
    MQTT_ADV_LINK_ENABLE: zYesNo.optional(),
    MQTT_ADV_LINK_BOOT: zYesNo.optional(),
    MQTT_ADV_LINK_CRON: zYesNo.optional(),
    MQTT_ADV_LINK_CRONTAB: z.string().optional(),
    MQTT_ADV_LINK_TOPIC: z.string().optional(),
    MQTT_ADV_LINK_RETAIN: z.string().optional(),
    MQTT_ADV_LINK_QOS: z.string().optional(),
    MQTT_ADV_INFO_GLOBAL_ENABLE: zYesNo.optional(),
    MQTT_ADV_INFO_GLOBAL_BOOT: zYesNo.optional(),
    MQTT_ADV_INFO_GLOBAL_CRON: zYesNo.optional(),
    MQTT_ADV_INFO_GLOBAL_CRONTAB: z.string().optional(),
    MQTT_ADV_INFO_GLOBAL_TOPIC: z.string().optional(),
    MQTT_ADV_INFO_GLOBAL_RETAIN: z.string().optional(),
    MQTT_ADV_INFO_GLOBAL_QOS: z.string().optional(),
    MQTT_ADV_CAMERA_SETTING_ENABLE: zYesNo.optional(),
    MQTT_ADV_CAMERA_SETTING_BOOT: zYesNo.optional(),
    MQTT_ADV_CAMERA_SETTING_CRON: zYesNo.optional(),
    MQTT_ADV_CAMERA_SETTING_CRONTAB: z.string().optional(),
    MQTT_ADV_CAMERA_SETTING_TOPIC: z.string().optional(),
    MQTT_ADV_CAMERA_SETTING_RETAIN: z.string().optional(),
    MQTT_ADV_CAMERA_SETTING_QOS: z.string().optional(),
    MQTT_ADV_TELEMETRY_ENABLE: zYesNo.optional(),
    MQTT_ADV_TELEMETRY_BOOT: zYesNo.optional(),
    MQTT_ADV_TELEMETRY_CRON: zYesNo.optional(),
    MQTT_ADV_TELEMETRY_CRONTAB: z.string().optional(),
    MQTT_ADV_TELEMETRY_TOPIC: z.string().optional(),
    MQTT_ADV_TELEMETRY_RETAIN: z.string().optional(),
    MQTT_ADV_TELEMETRY_QOS: z.string().optional(),
    HOMEASSISTANT_ENABLE: zYesNo.optional(),
    HOMEASSISTANT_BOOT: zYesNo.optional(),
    HOMEASSISTANT_CRON: zYesNo.optional(),
    HOMEASSISTANT_CRONTAB: z.string().optional(),
    HOMEASSISTANT_MQTT_PREFIX: z.string().optional(),
    HOMEASSISTANT_NAME: z.string().optional(),
    HOMEASSISTANT_IDENTIFIERS: z.string().optional(),
    HOMEASSISTANT_MANUFACTURER: z.string().optional(),
    HOMEASSISTANT_MODEL: z.string().optional(),
    HOMEASSISTANT_RETAIN: z.string().optional(),
    HOMEASSISTANT_QOS: z.string().optional()
});

/**
 * Documentation-derived shape of `getConfigs?conf=ptz_presets`. Keys are
 * numeric index strings ("0", "1", ...) mapping to preset names (empty when
 * unset). Not referenced by the operation. Omits the NULL sentinel.
 */
export const zPtzPresetsConf = z.record(z.string(), z.string());

/**
 * Documentation-derived shape of `getConfigs?conf=proxychains`. The script
 * returns a single PROXYCHAINS_SERVERS field (semicolon-joined server lines
 * from the [ProxyList] section), injected raw. Omits the NULL sentinel.
 */
export const zProxychainsConf = z.object({
    PROXYCHAINS_SERVERS: z.string().optional()
});

export const zSetCameraSettingsQuery = z.object({
    switch_on: z.string().optional(),
    save_video_on_motion: z.string().optional(),
    motion_detection: zYesNo.optional(),
    sensitivity: z.enum([
        'low',
        'medium',
        'high'
    ]).optional(),
    ai_human_detection: z.string().optional(),
    ai_vehicle_detection: z.string().optional(),
    ai_animal_detection: z.string().optional(),
    face_detection: z.string().optional(),
    motion_tracking: z.string().optional(),
    sound_detection: z.string().optional(),
    sound_sensitivity: z.enum([
        '30',
        '35',
        '40',
        '45',
        '50',
        '60',
        '70',
        '80',
        '90'
    ]).optional(),
    led: z.string().optional(),
    ir: z.string().optional(),
    rotate: z.string().optional(),
    cruise: z.enum([
        'no',
        'presets',
        '360'
    ]).optional()
});

/**
 * Always returned (success or validation failure). Check the error field.
 */
export const zSetCameraSettingsResponse = zSimpleResult;

export const zGetConfigsQuery = z.object({
    conf: z.enum([
        'camera',
        'system',
        'mqtt',
        'mqtt_advertise',
        'proxychains',
        'ptz_presets'
    ]).optional()
});

/**
 * Always returned. A validation failure is `{"error":"true"}`; a missing
 * file is `{"NULL":"NULL"}`; otherwise the conf contents plus the trailing
 * NULL sentinel.
 */
export const zGetConfigsResponse2 = zGetConfigsResponse;

/**
 * Flat KEY->value map. See operation description for special keys.
 */
export const zSetConfigsBody = z.record(z.string(), z.string());

export const zSetConfigsQuery = z.object({
    conf: z.enum([
        'camera',
        'system',
        'mqtt',
        'mqtt_advertise',
        'proxychains',
        'ptz_presets'
    ]).optional()
});

/**
 * Always returned. `{"error":"true"}` on invalid query/body/key, else `{"error":"false"}` (even if individual writes no-op).
 */
export const zSetConfigsResponse = zSimpleResult;

/**
 * Device telemetry (always).
 */
export const zGetStatusResponse = zStatusInfo;

/**
 * A JavaScript assignment statement (always).
 */
export const zGetHostnameResponse = z.string();

/**
 * Stream/snapshot links (always). Stream fields are conditional.
 */
export const zGetLinksResponse = zLinksResponse;

export const zTestProxyQuery = z.object({
    proxy: z.string()
});

/**
 * Always returned. `result` present on success (raw ipinfo.io JSON), absent on the error paths.
 */
export const zTestProxyResponse = zProxyResult;

/**
 * List of event directories (always).
 */
export const zGetEventDirsResponse = zEventDirsResponse;

export const zGetEventFilesQuery = z.object({
    dirname: z.string()
});

/**
 * Recordings in the directory, or `{"error":"true"}` if dirname is missing/rejected.
 */
export const zGetEventFilesResponse = zEventFilesResponse;

export const zDeleteEventDirQuery = z.object({
    dir: z.string().optional()
});

/**
 * Always `{"error":"false"}` on the pass path (even on no-op), `{"error":"true"}` on a blocklisted query string.
 */
export const zDeleteEventDirResponse = zSimpleResult;

export const zDeleteEventFileQuery = z.object({
    file: z.string()
});

/**
 * `{"error":"false"}` on success (even if files absent), `{"error":"true"}` on missing/invalid file.
 */
export const zDeleteEventFileResponse = zSimpleResult;

export const zGetSnapshotQuery = z.object({
    res: z.enum(['low', 'high']).optional().default('high'),
    watermark: zYesNo.optional(),
    base64: zYesNo.optional(),
    file: z.string().optional()
});

/**
 * JPEG (binary or base64) on the image paths, or JSON on the save-to-disk
 * and validation-failure paths. Content type indicates which.
 */
export const zGetSnapshotResponse = zSimpleResult;

export const zStartRecordingQuery = z.object({
    time: z.string().optional().default('60')
});

/**
 * `{"error":"false"}` on success/default, `{"error":"true"}` on invalid query string or non-numeric time.
 */
export const zStartRecordingResponse = zSimpleResult;

export const zGetLastRecordedVideoQuery = z.object({
    oldness: z.string().optional().default('0'),
    type: z.enum([
        '1',
        '2',
        '3',
        '4'
    ]).optional().default('1')
});

/**
 * Plain-text path/URL (type 1/2), raw mp4 (type 3/4), or JSON error on a
 * blocklisted query string. Content type indicates which.
 */
export const zGetLastRecordedVideoResponse = zSimpleResult;

export const zTimelapseQuery = z.object({
    action: z.enum(['list', 'delete']),
    file: z.string().optional()
});

/**
 * For action=list, a records object; for action=delete, `{"error":...}`.
 * For any other action the body is EMPTY with no Content-type header.
 */
export const zTimelapseResponse = z.union([
    zTimelapseListResponse,
    zSimpleResult
]);

export const zPtzMoveQuery = z.object({
    action: z.enum([
        'step',
        'abs',
        'rel',
        'cont'
    ]).optional().default('step'),
    x: z.string().optional(),
    y: z.string().optional(),
    dir: z.string().optional(),
    time: z.string().optional().default('0.3')
});

/**
 * `{"error":"false"}` whenever the query validates - this does NOT imply an
 * action was executed (action=step/cont with dir omitted or `none` moves
 * nothing yet still returns error=false). `{"error":"true"}` on an unknown
 * action or any validator failure.
 */
export const zPtzMoveResponse = zSimpleResult;

export const zPtzPresetQuery = z.object({
    action: z.enum([
        'go_preset',
        'add_preset',
        'del_preset',
        'set_home_position'
    ]),
    num: z.string().optional(),
    name: z.string().optional()
});

/**
 * `{"error":"false"}` when the external script succeeds (empty stdout),
 * else `{"error":"true","message":"<msg>"}` (Invalid query, Wrong
 * arguments, -99, or raw backend text). NOTE: multi-word backend messages
 * (e.g. "Preset number out of range") are word-split across repeated printf
 * format cycles, producing malformed JSON with extra unquoted-comma
 * key/value pairs; `message` then holds only the first word.
 */
export const zPtzPresetResponse = zPresetResult;

/**
 * Required only for action=save. Single-line JSON object of Wi-Fi credentials.
 */
export const zWifiBody = zWifiSaveRequest;

export const zWifiQuery = z.object({
    action: z.enum(['scan', 'save'])
});

/**
 * For action=scan, `{"wifi":[...]}`; for action=save, `{"error":...}`. Any
 * other action returns an empty body with no Content-type header.
 */
export const zWifiResponse = z.union([
    zWifiScanResponse,
    zSimpleResult
]);

/**
 * UTF-8 text to speak (first line only is used).
 */
export const zSpeakTextBody = z.string();

export const zSpeakTextQuery = z.object({
    lang: z.string().optional().default('en-US'),
    vol: z.string().optional(),
    voldb: z.string().optional()
});

/**
 * `{"error":"false","description":"<text>"}` on success, else
 * `{"error":"true","description":"<reason>"}`. Some failure paths omit the
 * Content-type header.
 */
export const zSpeakTextResponse = zAudioResult;

/**
 * Audio payload - multipart/form-data file field or a raw PCM/WAV stream.
 */
export const zPlayAudioBody = z.object({
    file: z.string().optional()
});

export const zPlayAudioQuery = z.object({
    vol: z.string().optional(),
    voldb: z.string().optional()
});

/**
 * `{"error":"false","description":""}` on success (mounted path returns
 * before playback finishes), else `{"error":"true","description":"<reason>"}`.
 */
export const zPlayAudioResponse = zAudioResult;

/**
 * Filename relative to /tmp/sd/audio (first line only; unvalidated, path traversal possible).
 */
export const zPlayAudioFileBody = z.string();

export const zPlayAudioFileQuery = z.object({
    voldb: z.string().optional()
});

/**
 * `{"error":"false","description":"<filename>"}` on success, else an error
 * object. The not-found and audio-disabled paths emit MALFORMED JSON.
 */
export const zPlayAudioFileResponse = zAudioResult;

export const zFirmwareUpgradeQuery = z.object({
    get: z.enum(['info', 'upgrade'])
});

/**
 * JSON version info for get=info; text/html status for get=upgrade; JSON
 * error on a blocklisted query string; empty body for an unrecognised get.
 */
export const zFirmwareUpgradeResponse = zFwInfoResponse;

/**
 * Always `{"error":"false"}`, sent just before the reboot.
 */
export const zRebootResponse = zSimpleResult;

/**
 * Always `{"error":"false"}`, even if the underlying rm/tar failed.
 */
export const zResetConfigResponse = zSimpleResult;

/**
 * Binary bzip2 tar archive (always).
 */
export const zSaveConfigResponse = z.string();

/**
 * Multipart upload of a config.tar.bz2 in the `files[]` field. Max 10000 bytes.
 */
export const zLoadConfigBody = z.object({
    'files[]': z.string().optional()
});

/**
 * text/html "Upload completed successfully, restart your camera" or
 * "Upload failed". An over-size upload returns an empty body.
 */
export const zLoadConfigResponse = z.string();

export const zControlServiceQuery = z.object({
    name: z.enum([
        'rtsp',
        'onvif',
        'wsdd',
        'ftpd',
        'mqtt',
        'mqtt-config',
        'mp4record',
        'all'
    ]).optional(),
    action: z.enum([
        'start',
        'stop',
        'status'
    ]).optional(),
    param1: z.string().optional(),
    param2: z.string().optional()
});

/**
 * `{"status":"..."}` for a matched status query, `{}` for start/stop and
 * unmatched requests, `{"error":"true"}` for a blocklisted query string.
 */
export const zControlServiceResponse = zServiceResult;
