/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CameraSettingsRouteImport } from './routes/camera-settings'
import { Route as ConfigurationsRouteImport } from './routes/configurations'
import { Route as ConfigurationsOnvifRouteImport } from './routes/configurations-onvif'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as MqttRouteImport } from './routes/mqtt'
import { Route as MqttAdvRouteImport } from './routes/mqtt-adv'
import { Route as ProxyRouteImport } from './routes/proxy'
import { Route as PtzRouteImport } from './routes/ptz'
import { Route as SnapshotRouteImport } from './routes/snapshot'
import { Route as SpeakRouteImport } from './routes/speak'
import { Route as StaticIpRouteImport } from './routes/static-ip'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TimelapseRouteImport } from './routes/timelapse'
import { Route as TzRouteImport } from './routes/tz'
import { Route as WifiRouteImport } from './routes/wifi'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsDirRouteImport } from './routes/events.$dir'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraSettingsRoute = CameraSettingsRouteImport.update({
  id: '/camera-settings',
  path: '/camera-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationsRoute = ConfigurationsRouteImport.update({
  id: '/configurations',
  path: '/configurations',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigurationsOnvifRoute = ConfigurationsOnvifRouteImport.update({
  id: '/configurations-onvif',
  path: '/configurations-onvif',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const MqttRoute = MqttRouteImport.update({
  id: '/mqtt',
  path: '/mqtt',
  getParentRoute: () => rootRouteImport,
} as any)
const MqttAdvRoute = MqttAdvRouteImport.update({
  id: '/mqtt-adv',
  path: '/mqtt-adv',
  getParentRoute: () => rootRouteImport,
} as any)
const ProxyRoute = ProxyRouteImport.update({
  id: '/proxy',
  path: '/proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const PtzRoute = PtzRouteImport.update({
  id: '/ptz',
  path: '/ptz',
  getParentRoute: () => rootRouteImport,
} as any)
const SnapshotRoute = SnapshotRouteImport.update({
  id: '/snapshot',
  path: '/snapshot',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakRoute = SpeakRouteImport.update({
  id: '/speak',
  path: '/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticIpRoute = StaticIpRouteImport.update({
  id: '/static-ip',
  path: '/static-ip',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelapseRoute = TimelapseRouteImport.update({
  id: '/timelapse',
  path: '/timelapse',
  getParentRoute: () => rootRouteImport,
} as any)
const TzRoute = TzRouteImport.update({
  id: '/tz',
  path: '/tz',
  getParentRoute: () => rootRouteImport,
} as any)
const WifiRoute = WifiRouteImport.update({
  id: '/wifi',
  path: '/wifi',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsDirRoute = EventsDirRouteImport.update({
  id: '/events/$dir',
  path: '/events/$dir',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/camera-settings': typeof CameraSettingsRoute
  '/configurations': typeof ConfigurationsRoute
  '/configurations-onvif': typeof ConfigurationsOnvifRoute
  '/maintenance': typeof MaintenanceRoute
  '/mqtt': typeof MqttRoute
  '/mqtt-adv': typeof MqttAdvRoute
  '/proxy': typeof ProxyRoute
  '/ptz': typeof PtzRoute
  '/snapshot': typeof SnapshotRoute
  '/speak': typeof SpeakRoute
  '/static-ip': typeof StaticIpRoute
  '/status': typeof StatusRoute
  '/timelapse': typeof TimelapseRoute
  '/tz': typeof TzRoute
  '/wifi': typeof WifiRoute
  '/events/$dir': typeof EventsDirRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/camera-settings': typeof CameraSettingsRoute
  '/configurations': typeof ConfigurationsRoute
  '/configurations-onvif': typeof ConfigurationsOnvifRoute
  '/maintenance': typeof MaintenanceRoute
  '/mqtt': typeof MqttRoute
  '/mqtt-adv': typeof MqttAdvRoute
  '/proxy': typeof ProxyRoute
  '/ptz': typeof PtzRoute
  '/snapshot': typeof SnapshotRoute
  '/speak': typeof SpeakRoute
  '/static-ip': typeof StaticIpRoute
  '/status': typeof StatusRoute
  '/timelapse': typeof TimelapseRoute
  '/tz': typeof TzRoute
  '/wifi': typeof WifiRoute
  '/events/$dir': typeof EventsDirRoute
  '/events': typeof EventsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/camera-settings': typeof CameraSettingsRoute
  '/configurations': typeof ConfigurationsRoute
  '/configurations-onvif': typeof ConfigurationsOnvifRoute
  '/maintenance': typeof MaintenanceRoute
  '/mqtt': typeof MqttRoute
  '/mqtt-adv': typeof MqttAdvRoute
  '/proxy': typeof ProxyRoute
  '/ptz': typeof PtzRoute
  '/snapshot': typeof SnapshotRoute
  '/speak': typeof SpeakRoute
  '/static-ip': typeof StaticIpRoute
  '/status': typeof StatusRoute
  '/timelapse': typeof TimelapseRoute
  '/tz': typeof TzRoute
  '/wifi': typeof WifiRoute
  '/events/$dir': typeof EventsDirRoute
  '/events/': typeof EventsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/camera-settings'
    | '/configurations'
    | '/configurations-onvif'
    | '/maintenance'
    | '/mqtt'
    | '/mqtt-adv'
    | '/proxy'
    | '/ptz'
    | '/snapshot'
    | '/speak'
    | '/static-ip'
    | '/status'
    | '/timelapse'
    | '/tz'
    | '/wifi'
    | '/events/$dir'
    | '/events/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/camera-settings'
    | '/configurations'
    | '/configurations-onvif'
    | '/maintenance'
    | '/mqtt'
    | '/mqtt-adv'
    | '/proxy'
    | '/ptz'
    | '/snapshot'
    | '/speak'
    | '/static-ip'
    | '/status'
    | '/timelapse'
    | '/tz'
    | '/wifi'
    | '/events/$dir'
    | '/events'
  id:
    | '__root__'
    | '/'
    | '/camera-settings'
    | '/configurations'
    | '/configurations-onvif'
    | '/maintenance'
    | '/mqtt'
    | '/mqtt-adv'
    | '/proxy'
    | '/ptz'
    | '/snapshot'
    | '/speak'
    | '/static-ip'
    | '/status'
    | '/timelapse'
    | '/tz'
    | '/wifi'
    | '/events/$dir'
    | '/events/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CameraSettingsRoute: typeof CameraSettingsRoute
  ConfigurationsRoute: typeof ConfigurationsRoute
  ConfigurationsOnvifRoute: typeof ConfigurationsOnvifRoute
  MaintenanceRoute: typeof MaintenanceRoute
  MqttRoute: typeof MqttRoute
  MqttAdvRoute: typeof MqttAdvRoute
  ProxyRoute: typeof ProxyRoute
  PtzRoute: typeof PtzRoute
  SnapshotRoute: typeof SnapshotRoute
  SpeakRoute: typeof SpeakRoute
  StaticIpRoute: typeof StaticIpRoute
  StatusRoute: typeof StatusRoute
  TimelapseRoute: typeof TimelapseRoute
  TzRoute: typeof TzRoute
  WifiRoute: typeof WifiRoute
  EventsDirRoute: typeof EventsDirRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera-settings': {
      id: '/camera-settings'
      path: '/camera-settings'
      fullPath: '/camera-settings'
      preLoaderRoute: typeof CameraSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurations': {
      id: '/configurations'
      path: '/configurations'
      fullPath: '/configurations'
      preLoaderRoute: typeof ConfigurationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configurations-onvif': {
      id: '/configurations-onvif'
      path: '/configurations-onvif'
      fullPath: '/configurations-onvif'
      preLoaderRoute: typeof ConfigurationsOnvifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mqtt': {
      id: '/mqtt'
      path: '/mqtt'
      fullPath: '/mqtt'
      preLoaderRoute: typeof MqttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mqtt-adv': {
      id: '/mqtt-adv'
      path: '/mqtt-adv'
      fullPath: '/mqtt-adv'
      preLoaderRoute: typeof MqttAdvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proxy': {
      id: '/proxy'
      path: '/proxy'
      fullPath: '/proxy'
      preLoaderRoute: typeof ProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ptz': {
      id: '/ptz'
      path: '/ptz'
      fullPath: '/ptz'
      preLoaderRoute: typeof PtzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/snapshot': {
      id: '/snapshot'
      path: '/snapshot'
      fullPath: '/snapshot'
      preLoaderRoute: typeof SnapshotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speak': {
      id: '/speak'
      path: '/speak'
      fullPath: '/speak'
      preLoaderRoute: typeof SpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/static-ip': {
      id: '/static-ip'
      path: '/static-ip'
      fullPath: '/static-ip'
      preLoaderRoute: typeof StaticIpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timelapse': {
      id: '/timelapse'
      path: '/timelapse'
      fullPath: '/timelapse'
      preLoaderRoute: typeof TimelapseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tz': {
      id: '/tz'
      path: '/tz'
      fullPath: '/tz'
      preLoaderRoute: typeof TzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wifi': {
      id: '/wifi'
      path: '/wifi'
      fullPath: '/wifi'
      preLoaderRoute: typeof WifiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$dir': {
      id: '/events/$dir'
      path: '/events/$dir'
      fullPath: '/events/$dir'
      preLoaderRoute: typeof EventsDirRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CameraSettingsRoute: CameraSettingsRoute,
  ConfigurationsRoute: ConfigurationsRoute,
  ConfigurationsOnvifRoute: ConfigurationsOnvifRoute,
  MaintenanceRoute: MaintenanceRoute,
  MqttRoute: MqttRoute,
  MqttAdvRoute: MqttAdvRoute,
  ProxyRoute: ProxyRoute,
  PtzRoute: PtzRoute,
  SnapshotRoute: SnapshotRoute,
  SpeakRoute: SpeakRoute,
  StaticIpRoute: StaticIpRoute,
  StatusRoute: StatusRoute,
  TimelapseRoute: TimelapseRoute,
  TzRoute: TzRoute,
  WifiRoute: WifiRoute,
  EventsDirRoute: EventsDirRoute,
  EventsIndexRoute: EventsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
